### ISSUE TITLE
Sentence "Hide Local Thumbnails" is not translated (Spanish)

### ISSUE THREAD

**Issue by marco4mp** [elementary/files#1020]
Sentence: "Hide Local Thumbnails".  It is not translated into Spanish.

![2019-08-09-22h02m22s270](https://user-images.githubusercontent.com/52709674/62816349-a5068d00-baf3-11e9-8d68-a96a0c5f5f95.png)

**Comment by ryonakano** [comment]
It looks like the corresponding string has not reviewed and saved (because it's marked as `fuzzy`):

https://github.com/elementary/files/blob/33555e446d2cdf652f1ffff7981990b293845303/po/es.po#L659-L662

I think this string will be shown as translated once the translation is revised/saved and a new release of Files is released.

**Comment by tintou** [comment]
You can contribute to the translation here https://l10n.elementary.io/projects/files/files/es/ once the string is translated, you have to wait for a new Files release to enjoy your translation. Closing as there is no action to do from our side.
