### ISSUE TITLE
[feature request] If historyis  disabled on privacy settings hide "Recently used" left panel item

### ISSUE THREAD

**Issue by queeup** [elementary/files#1039]
Like title explained. If history is disabled on privacy settings hide "Recently used" left panel item.

**Comment by danrabbit** [comment]
I think we’ve had this come up previously and we don’t want to do this because:

* having history disabled at the moment doesn’t mean you don’t have any previous history.

* users may not understand what disabling history does, so we want to make sure features are still discoverable and can easily be enabled if the user changes their mind

**Comment by queeup** [comment]
OK. I understand. I am closing then. Thank you.
