### ISSUE TITLE
Zstandard support for file compression

### ISSUE THREAD

**Issue by PlatonB** [elementary/files#1068]

**Comment by danrabbit** [comment]
OP, in the future please be more descriptive when reporting an issue.

I'm guessing this is about the compress option from the right click menu? This functionality is provided by an app called File Roller. You can file issues against File Roller here: https://gitlab.gnome.org/GNOME/file-roller/issues/

Closing since this is not actually an issue with Files and it cannot be solved within the scope of the Files codebase

**Comment by PlatonB** [comment]
@danrabbit yes, via right-click menu. It seems to me, there is no other way to compress anything in Files, so I decided not to create a description of this feature request.

> This functionality is provided by an app called File Roller.

Thanks for the clarification! It is unlikely that I could know, which backend is used for compression offered by Files, because this information is not explicitly provided.

**Comment by PlatonB** [comment]
Maybe it is better to reopen issue for third-party developers? I think it's a good idea to make a zstd-archiver for the AppCenter with integration into the context menu.
