### ISSUE TITLE
Permanent file deletion dialog should have .destructive-action on the Delete button

### ISSUE THREAD

**Issue by Exalm** [elementary/files#1101]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

![Screenshot from 2019-11-06 12-55-07](https://user-images.githubusercontent.com/1510457/68279248-ebc04080-006a-11ea-91ef-081da40c2964.png)

The Delete button does a dangerous action that cannot be undone. I think it makes sense to have it in red.

### To Reproduce
1. Try shift-deleting any flie

- [x] I'm using the latest version from git that I've manually compiled

**Comment by cassidyjames** [comment]
If someone is looking at touching this dialog up, I have some copy thoughts. :)

>#### Permanently delete “Videos”?
>Deleted items are not sent to Trash and are not recoverable.
>
>    `Cancel`  **`Delete`**

**Comment by mcclurgm** [comment]
I'd like to give this a shot, but I would appreciate some design help.

Since the delete dialog uses a generic dialog from the `run_warning` function, we would either have to special-case it somehow or make larger changes to the dialog codebase. It looks like half the functions that call `run_warning` are confirmations of destructive actions and could benefit from a similar change (like delete from trash). But many others aren't (like error messages from copying files). 

My instinct is to create a new type of dialog function like `run_confirmation` that would be for destructive actions like this. I think that this sounds semantically different from a status warning, and the other destructive confirmations could benefit from this fix. Is this a good way to go about a fix here, or is it too big?

**Comment by jeremypw** [comment]
The simplest way would be to apply the destructive-action style to any button titled `DELETE` or `DELETE_ALL` .  You would need to define the button title constants in a way that makes them available to both marlin-file-operations.c and to StockDialogs.vala.  One way to do this is to move the definitions into StockDialogs.vala but outside any namespace (if you namespace them you would need to amend their use in marlin-file-operations.c accordingly).

**Comment by mcclurgm** [comment]
That makes sense. I have one reservation about this method though. "Delete" and "Delete All" are not the only actions that are destructive and could use this. One example is "Empty Trash," which isn't given a constant. I could of course create a constant for it. But this begs the question of whether we want to define a constant for every possible destructive button label, and then check for every one of them.

**Comment by jeremypw** [comment]
"Empty Trash" already has destructive action styling in Trash View.  (It doesn't in the trash context menu but I am not sure if it usual to add styling to menu items). I agree my proposal only makes sense if there is a very limited set of destructive (non-undoable) file operations. Most file operations are (or should be) undoable. Do you have any other examples?

**Comment by jeremypw** [comment]
Actually, I forgot that after pressing the "Empty Trash" button you get a confirmation dialog and that should have a destructive action styled button.

**Comment by jeremypw** [comment]
I think that there are only three irreversible file operations (delete, delete_all, empty_trash). (Deleting a selection of files from trash does not give rise to a confirmation dialog).  Changing permission is not currently reversible but it is intended to be and I do not think it is a destructive action.

**Comment by mcclurgm** [comment]
I'm not sure which of these are actually in use and would require cases, but in `marlin_file_operations.c` there are a couple more actions that seem irreversible. One is `REPLACE` and `REPLACE_ALL`, which I actually don't think is used anywhere in the codebase and could potentially be removed. The other is emptying the trash, which you found too.

So now that I've thought about it more, this is definitely few enough that this implementation makes sense. I think that it's probably the way to go, since I think this is probably about the least invasive way to implement this sort of change.
