### ISSUE TITLE
The new git plugin freezes Files with large repository

### ISSUE THREAD

**Issue by tintou** [elementary/files#1103]
Step 1: clone [LibreOffice](https://github.com/LibreOffice/core/)
Step 2: go to the directory with Files
Step 2 makes Files freeze. The git plugin should probably use a separate thread (with a Cancellable)

**Comment by jeremypw** [comment]
Probably due to doing a recursive enumeration of all the files under a directory to determine whether any of them have a relevant git status, which is then applied to the displayed folder.  So a folder shows "modified" if it contains any modified file or folder.  As you say, this needs to be done async (maybe showing an appropriate "working" emblem until finished?)

**Comment by jeremypw** [comment]
I think there is a smarter way of doing this using StatusOptions ...
