### ISSUE TITLE
file:/// prefix in folder path

### ISSUE THREAD

**Issue by PlatonB** [elementary/files#1146]
## Prerequisites
- [+] I have searched open and closed issues for duplicates.

## Describe the bug
In version 4.3.0, an inconvenience appeared: instead of the usual folder path, the path with the prefix file:/// is displayed.

### To Reproduce
1. Go to any folder. I will cite /home/platon/miniconda3/bin as an example.
2. Click at the right of the breadcrumbs.
You will see the path like file:///home/platon/miniconda3/bin

### Expected behavior
In previous versions, the path began with /home. It was much more convenient if you needed to copy the path to a terminal or another program.

## Platform Information
elementary OS 5.1

Please check what applies:
- [+] I'm using the latest released stable version

**Comment by aljelly** [comment]
It also happens when copying files, `file://` is placed at the beginning of the path when you paste it into e.g. the terminal (just in case the PR doesn't fix that too).

### Steps to reproduce:
1. Copy a file in Files
2. Paste it into something that accepts text (e.g. terminal)

### Expected result:
A file path, like `/home/user/test`

### Actual result:
A URL (like `file:///home/user/test`)

**Comment by jeremypw** [comment]
Thanks. The PR only fixes the pathbar issue.  DnD works OK with the terminal - i.e. you can drag a folder onto the terminal and a quoted path is pasted in.  So I agree that using cut and paste should work the same way.
