### ISSUE TITLE
Context menu with hexa code ?

### ISSUE THREAD

**Issue by BellemareMederic** [elementary/files#1188]
Hello there, tooday i try to make a new file in files explorer and this context menu get dirty of i dont know what and when :| do you know where i need to go to change that context menu ?
![Capture d'écran de 2020-01-24 22 16 34](https://user-images.githubusercontent.com/6710664/73115716-dc2cf700-3ef7-11ea-8ff6-5a34de1c6df2.png)

my fresh installation of elementary os have 1.5 years

Linux mederic-msi 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by jeremypw** [comment]
@BellemareMederic What have you in your `~/Templates` folder?  The "New ..." submenu shows, below the "New File" item, the contents of that folder.  The Templates folder is intended to contains files that are useful as templates for new files i.e. the new file starts as a copy of the chosen template file rather than as an empty file.

**Comment by BellemareMederic** [comment]
yep this is the problem. i move my home directory to other /media and made a symlink and Templates has reset in XDG. i just create Template folder and reconfigure my XDG and now is ok. 

https://wiki.archlinux.org/index.php/XDG_user_directories
