### ISSUE TITLE
File whose content consists of “//” is assumed to be a C source code file

### ISSUE THREAD

**Issue by KomalleanaByzantis** [elementary/files#1205]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

A file whose content solely consists of “//” is assumed to be a C source code file. This behaviour applies to both Files and Code.

## To reproduce

1. Open Files.
2. Create an empty file.
3. Open the file in Code and enter the text “//”.
4. Save the file and close it.
5. Refresh the view in Files.
6. The file is displayed as a C source code file. Open the file again.
7. Code treats the file like a C source code file and automatically opens the side bar, even though there is nothing to show and the language of the file is ambiguous.

## Expected behaviour

More requirements must be met before a file is assumed to be of a certain type. For example, a C source code file must end in `.c` or `.h` before it is concluded that it is written in C. There are likely other file types which should have similar additional requirements.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4140902/File.whose.content.consists.of.slashes.is.assumed.to.be.a.C.source.code.file.zip)

# Platform information

![System information](https://user-images.githubusercontent.com/51057001/73566487-4992d780-4464-11ea-9f77-39d1446d554a.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by aljelly** [comment]
I think may be more to do with system-wide mimetypes rather than Files itself:
```sh
$ echo "// hello" > c_test
$ file c_test
c_test: ASCII text
$ mimetype c_test
c_test: text/x-csrc
```
If we then run `mimetype -D c_test` (I literally just found out about this option now while trying to figure out what was causing this):
```
$ mimetype -D c_test
> Data dirs are: [...list of directories...]
> Checking inode type
> Checking globs for basename 'c_test'
> Value "//" at offset 2 matches at /usr/share/mime/magic line 1588
c_test: text/x-csrc
```
So the `//` at the start of the file is considered a [magic number](https://en.wikipedia.org/wiki/File_format#Magic_number), stored in the `/usr/share/mime/magic` file.

This is the particular line that is being looked at in `/usr/share/mime/magic` around line 1588 (lines 1586-1589) (anything with `^X` or similar is probably binary interpreted by `less`):
```
[30:text/x-csrc]
>0=^@^B/*
>0=^@^B//
>0=^@^H#include
```

This therefore isn't a bug (and Files and Code aren't causing it either!).

The concept of "magic numbers" in general means you don't necessarily need to have specific extensions on many types of files for the mimetype to be correctly identified. For example, you could remove `.png` from any PNG files you have and they would still be interpreted as PNG files. This is because at the beginning of the PNG files there is a binary sequence at the start of the file (this is what "magic number" refers to). Technically, one could say that `//` is just a particular binary sequence that just happens to be readable text, hence why `//` can be a "magic number". This concept of magic numbers is also what allows files starting with e.g. `#!/usr/bin/env bash` to be interpreted as a script executable with `bash`.

This is not the only way a file's mimetype can be identified however; file extensions are another way of the system being able to know about what the mimetype of the file is. For example, you could have a file with only "abc" in it (which does not match any magic number, certainly not the ones for C), yet if it were to end with `.c`, the file's mimetype will be determined to be C source code. You can see this in the `/usr/share/mime/text/x-csharp.xml` file:

```xml
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="text/x-csrc">
  <!--Created automatically by update-mime-database. DO NOT EDIT!-->
  <comment>C source code</comment>
  ...
  <sub-class-of type="text/plain"/>
  <alias type="text/x-c"/>
  <glob pattern="*.c" case-sensitive="true"/>
</mime-type>
```

This particular form of identifying files by their extension is (as you might be able to guess from looking at it) a freedesktop standard.

Okay, okay, anyway, if you really don't like this particular interpretation of your files, you could try removing line 1588 in `/usr/share/mime/magic` (make a backup of it first though! `sudo cp /usr/share/mime/magic /usr/share/mime/magic.bk`) and then running `sudo update-mime-database /usr/share/mime/`.

**Comment by KomalleanaByzantis** [comment]
@aljelly I, a normal user, would rather not have to edit system files in order to prevent what I would expect to be plain text files or shell scripts at best from being confused for source code files in various arbitrary programming languages. I appreciate the level of detail in your reply, but I am not particularly interested in the specifics of why this behaivour occurs. From the perspective of a normal user, i.e. myself, the apparent behaviour witnessed in Files and Code is strange.

I should note that in some exercises in my computer science education, I have had issues where Files would not correctly identify the programming languages of certain files despite the clear presence of a file extension. I have had the mispleasure of using the programming language F#, but where my source code files would sometimes be considered a mixture of plain text files, C source code, and F# source code. I have not attempted to reproduce this behaviour.

**Comment by jeremypw** [comment]
Files relies on library functions provided by the system to identify files from the extension or contents.  Hopefully, as elementary moves to more recent versions of the libraries such issues will diminish.  I do not think this is an issue that can realistically be fixed or worked around in Files, so marking "Out of Scope"

**Comment by jeremypw** [comment]
That being said, if you find Files is performing less well than say Nautilus or Code is performing less well that say Gedit *when running with the same libraries* then it may be worth another look.

**Comment by aljelly** [comment]
I believe the problem with your F# files may be because the system doesn't have anything telling it your files are F# files. In other words there's nothing for it in the mime database. Because of this the system thinks your e.g. `.fs` files are just plain text files and sometimes C source files (I guess because some of them start with `//`).

If you want to fix your F# files, you could create a file in `~/.local/share/mime/packages/x-fsharp.xml` containing:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="text/x-fsharp">
    <generic-icon name="text-x-source"/>
    <glob pattern="*.fs"/>
    <glob pattern="*.fsi"/>
    <glob pattern="*.fsx"/>
    <glob pattern="*.fsscript"/>
    <comment>F# source code</comment>
  </mime-type>
</mime-info>
```

And then run `update-mime-database ~/.local/share/mime/`.

Here's some quick steps for doing this (I've tested it, it works):
1. Open Terminal
2. Run `io.elementary.code ~/.local/share/mime/packages/x-fsharp.xml`
3. This will open Code with a blank file. Paste in the XML code block from above.
4. Save and exit.
5. Run `update-mime-database ~/.local/share/mime/`

Now Files will know your files are F#. The only thing is however that you'll find your F# files aren't associated with any program now, but you can easily fix this by right clicking any one of your F# files, clicking Open with > Other Application, clicking "View All Applications" if necessary, and selecting Code.

What's also nice about this solution is that now Code will automatically select F# for the syntax highlighting, so it won't confuse them with "Fortran" or "Forth" (seriously, I have never heard of the latter language).

I guess it would be reasonable to suggest either to elementary or whoever is responsible for curating the mime files (Ubuntu? Debian?) to include an F# mime in the future, if the party responsible haven't already added such support files in-between Ubuntu 18.04 and 20.04 (the next Ubuntu LTS).

**Comment by KomalleanaByzantis** [comment]
@aljelly Thank you for your desire to assist me, but I am thankfully not working with the language F# any longer. In any case, I dislike temporary solutions and I would therefore not follow your guide. Hopefully it will assist someone who arrives at this page from a search engine.

@jeremypw I do not know what Nautilus or Gedit are, so I cannot comment. Nevertheless I disagree with the notion of using libraries which seem to make rather chaotic guesses, from my own experience. I digress.

**Comment by jeremypw** [comment]
@KomalleanaByzantis Nautilus is the default File Manager for Ubuntu/Gnome and Gedit is the default text editor for Ubuntu/Gnome.
