### ISSUE TITLE
Should not attempt to restore a folder on an unmounted device on startup

### ISSUE THREAD

**Issue by ghost** [elementary/files#1216]
# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

Opening the Files application after having unmounted an external device makes it attempt to navigate to the now-unmounted device, which it instead displays as a non-existent folder.

## To reproduce

1. Open Files.
2. Mount an external device such as a USB drive.
3. Close Files.
4. Physically remove the external device.
5. Open Files.
6. The application attempts to navigate to a location which does not exist, and a “this directory does not exist” message is shown.

## Expected behaviour

The application does not try to re-open a folder if it does not exist, regardless of whether it is an unmounted device or some other type of non-existent path. If all folders from the previous session no longer exist, the application opens the Home folder.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4144546/Opening.the.application.after.unmounting.an.external.device.makes.it.navigate.to.a.non-existent.folder.zip)

# Platform information

![System information 2](https://user-images.githubusercontent.com/51057001/73610820-c7c5ba00-45db-11ea-87eb-857fd71692e2.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by jeremypw** [comment]
I guess this would be possible to implement although it means distinguishing opening a folder on start-up (in which case ignore it) and opening at another time (in which case display the failure message). Not sure there is a significant downside to the existing behaviour though.

**Comment by aljelly** [comment]
I actually think this may not be a good idea design-wise. People might actually find it confusing or annoying that a tab keeps disappearing if a device is no longer present or if a folder otherwise does not exist anymore.

I think instead that, in the case of an unmounted device, it would be better to show a specific message in the view if Files detects that the folder missing is in `/media/` (or `/run/media/` in some distros). Files already shows a special breadcrumb for `/media/`, so I expect that part at least shouldn't be difficult.

The attempted path could be parsed so that a variable `label` would be `/media/user/LABEL` (_and_ `/media/user/LABEL/folder1/folder2/`) and then instead of this:

### Previous

![image](https://user-images.githubusercontent.com/10395308/73824718-89eeae80-47f2-11ea-893b-2b9cb4f4e0d3.png)

We could show something like this (I used `GTK_DEBUG=interactive`):

### New (for media)

![image](https://user-images.githubusercontent.com/10395308/73821296-84da3100-47eb-11ea-9b4d-7567ffd1b38a.png)

(of course exact wording can be tweaked, e.g. maybe "Try showing the media device again" would be better)

Probably ideally this `drive-removable-media` icon would have a `view-refresh` emblem (like the plus in the `folder-new` icon in the first image. This is the `view-refresh` emblem for reference:

![image](https://user-images.githubusercontent.com/10395308/73821223-53616580-47eb-11ea-9c7c-2df86894e32e.png)

If it's possible to detect and simple to implement, this could also be done for FUSE mounts (with a specific message for such a case), although Files would have to store somewhere that that specific tab was a FUSE mount when it's closed. The message would be like "Mount '[folderbasename]' can't be found. Did you forget to launch some app?".

If the folder does not exist and it's not a media device or FUSE mount, then the user should probably be told about it. Maybe it'll prompt them to look into why that folder has just disappeared unexpectedly, rather than have the tab for it just silently and mysteriously disappearing upon Files loading. I would find that confusing. What if my folder was a folder within a FUSE mount and I forgot to start the application that created the FUSE mount? I'll be like "Oops, I forgot to start the application for it, I'll do that now and press F5" rather than "I'll do that now and then tediously and manually navigate all the way back to it".

So, if a folder does not exist anymore (since Files was last closed) and it's not a media device or FUSE mount, possibly the message's title could be changed to "This Folder Does Not Exist _Anymore_", something like this (again, GTK inspector):

### New (for folders that don't exist since Files was closed)

![image](https://user-images.githubusercontent.com/10395308/73821746-83f5cf00-47ec-11ea-9faf-e7f21c158911.png)

There should also be an option to go home after the folder creation option:


### Go home option

![image](https://user-images.githubusercontent.com/10395308/73822082-39c11d80-47ed-11ea-9b7a-c534e0d59bd0.png)

I think for the "folder doesn't exist" screens, "Go Home" should be the first option and "Create" folder should be the second one. If "Go Home" is added to the "device/mount not found" screens, the "Retry" should be the first option and "Go Home" should be the second.

**Comment by KomalleanaByzantis** [comment]
@aljelly I support all of your suggestions and think that implementing such specialised screens would by far be the ideal result. I greatly appreciate that you provide illustrations of what you have in mind and that you have so carefully considered your proposals. My original suggestion in my error report was merely a simplified solution to the underlying problems so that this issue would not morph into a “wishlist” item.

**Comment by KomalleanaByzantis** [comment]
@jeremypw I am not part of the elementary OS team, and I do not mean to look as though I am “backseat moderating,” but perhaps this issue warrants having a Needs Design label attached to it?

**Comment by jeremypw** [comment]
My view is that if a user manually unplugs a USB devices they know that have done so and in all likelihood have finished using it.  Files should not try to second guess the user in this situation. So I have already created a PR fixing this issue.  However, you are probably right that UX team should sign off on it one way or another,
