### ISSUE TITLE
Wrong tabs are restored after a system restart

### ISSUE THREAD

**Issue by vikasnataraja** [elementary/files#1294]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
After I restart my computer, the wrong tabs are restored. It seems to restore tabs that I was using about 3 or 4 weeks ago and this occurs after every restart (i.e. after very restart, the exact same set of tabs are restored)

### To Reproduce
1. Go to Files
2. Open a bunch of tabs
3. Restart computer

### Expected behavior

The correct tabs i.e tabs that were being used right before the restart must be restored. 

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by jeremypw** [comment]
The only explanation for this I can think of is that, for some reason the last in use tabs are not being saved to settings when Files closes (they are not updated on the fly).  How do you close Files? I am not finding this problem using the latest version of Files.

**Comment by jeremypw** [comment]
If you have turned off "Remember History" for the last 3 - 4 weeks and just turned it back on then on the first start up the tabs you were using 3 - 4 weeks ago will be restored.  However Files should subsequently restore the latest tabs, unless you have turned off the "restore-tabs" setting, in which case it will start at your home directory.

**Comment by jeremypw** [comment]
It seems that if you log out without closing Files then the current tabs are not saved either. Looks like the system force closes the apps without allowing them to clean up :-(

**Comment by jeremypw** [comment]
Looks like Code get around this by inserting a handler for the Unix SIGTERM and SIGINT signals that calls the "quit" action of the app.  I guess this should be replicated in Files.

**Comment by jeremypw** [comment]
Correction: Code saves open tabs on the fly.  Handling SIGTERM/SIGINT does not work for logging out - uses SIGKILL (which cannot be caught)?

**Comment by jeremypw** [comment]
Looks like all apps failed to save their state if closed (killed) by logging out - so the only solution is saving state on the fly. Files is different from Code in that it is possible to navigate to different locations in the same tab but there is a 1:1 relation between documents and tabs in Code so there is less change.  Seeking design input on whether we want Files to save tab/location state on the fly.

**Comment by vikasnataraja** [comment]
I believe Terminal also saves states on the fly. Even if I restart abruptly i.e by not closing the apps first, it always restores my tabs correctly. Files, however, doesn't seem to do that.

**Comment by jeremypw** [comment]
Even if all elementary apps save state on the fly, it is probable that many (most?) 3rd party apps won't so its always going to be safer to close all windows before logging out.  Unless the logout code can be changed to close the windows properly?

**Comment by jeremypw** [comment]
Just noticed that there is already an (elderly) issue about this at https://github.com/elementary/wingpanel-indicator-session/issues/27

**Comment by follower** [comment]
Also related:

 * https://github.com/elementary/files/issues/620
 * https://github.com/elementary/files/issues/1744

Also, if I recall correctly, another variant of this issue is that tabs in multiple Files windows are not handled correctly--which ever window is closed last overwrites the state.

*time passes*

Actually, from looking at the code it seems the only saving tabs for one window behaviour is...intentional?

https://github.com/elementary/files/blob/1e6842fd91e8d2bfdf63e5c2341b7e0cf32ce3ab/src/View/Window.vala#L906-L910

(Although I am curious if how "first window" is determined has changed over time...)

Maybe saving tabs for all open windows on quit (+restore) needs a separate issue?

To me, not saving tabs in all windows on application exit is both non-obvious and non-useful behaviour.

Related commits:

 * https://github.com/elementary/files/commit/8e07adc7be5bfcbfb07bed1abfecf6c7129e6aec
 * https://github.com/elementary/files/commit/19fc026912c9d306da3acaee689d82a3917c8e4b (I don't fully understand the explanation given in this commit message.)
 * https://github.com/elementary/files/commit/fb243a7a44ed7db27cde83059e7e70a412caa525#diff-9f222932bff8d9ecb28b5c1f740d2e5f21a7d04d4e9a2b85623c32f463f6b0ca

Also:

https://github.com/elementary/files/blob/1e6842fd91e8d2bfdf63e5c2341b7e0cf32ce3ab/src/View/Window.vala#L976-L980
