### ISSUE TITLE
The left portion of the search bar is not clickable

### ISSUE THREAD

**Issue by ryonakano** [elementary/files#1328]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
![2020-05-18 11 44 31 の画面録画](https://user-images.githubusercontent.com/26003928/82169639-12eea900-98fd-11ea-8467-011c675fa984.gif)

The left portion of the search bar (where the placeholder "Search or" exists) is not clickable. I moved the pointer from right to left and tried to click the search bar each time, but it turned to unclickable at some point.

### To Reproduce
1. Open Files
2. Try to click the search bar. It's clickable and you can type some search term.
3. Move the mouse pointer onto the placeholder "Search or"
4. It's not clickable

### Expected behavior
The entire search bar should be clickable.

## Platform Information
- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version
- [x] I'm using the latest daily version: `4.4.2+r3826+pkg92~daily~ubuntu6.0.1`

**Comment by jeremypw** [comment]
This is caused by code that changes thestate when the cursor is over a breadcrumb.  Unfortunately it is not taking into account that when the placeholder is shown the breadcrumb is not drawn so it changes at the point where there would have been a breadcrumb.  If you right-click at this point you get the breadcrumb context menu.  Not sure whether we want to keep the context menu but I think the pathbar should be editable at that point.
