### ISSUE TITLE
Save file window vanishes when mouse cursor move to the top

### ISSUE THREAD

**Issue by level6sam** [elementary/files#1390]
When I want to save a file in Firefox (flatpak) the save file window disappears when I move the mouse cursor to the top of the save file window.

I have tried to replicate it in Linux Mint but was unable to do so. I'm not sure if this is a flatpak problem, a problem with elementary, or a flatpak problem with elementary.

I have attached a screen record to show you what I mean.

Thanks

App used: Firefox 78.0.3

[Screen record from 2020-07-11 01.37.32.mp4.zip](https://github.com/elementary/gala/files/4907676/Screen.record.from.2020-07-11.01.37.32.mp4.zip)

**Comment by jeremypw** [comment]
I could not reproduce this with the FireFox deb using the "save page as" function.  Using the "Download" function just downloaded the file to my Download folder without invoking the filechooser.

**Comment by jeremypw** [comment]
I could reproduce this with the FireFox flatpak.  It occurs when the pointer moves into the pathbar.

**Comment by jeremypw** [comment]
This seems to be a problem with calling `Gdk.Display.get_default ()` from within a flatpak. This does not just return `null`, it crashes the module.  The `pantheon-filechooser-module` calls this in order to change the cursor appearance when it is over the breadrumbs from the `edit` cursor to the `default` cursor.  I am not sure whether it is possible for an app to detect whether it is running as a flatpak but we can tell whether it is in the filechooser and disable that feature to avoid this crash.  Or is there a way of configuring the flatpak to allow this command to run?

**Comment by jeremypw** [comment]
The ultimate solution is for Files to provide a NativeFileChooser portal I guess. One of the warnings on starting Firefox flatpak up on the commandline is `Gtk-Message: 11:26:00.313: Failed to load module "pantheon-filechooser-module"`
``
