### ISSUE TITLE
Pointer cursor should only be used for folders

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1418]
I was gonna say we shouldn't use the pointer cursor at all, but I can see the argument that folders behave similarly enough to a browser link: clicking takes you to that location, you can middle-click to open in a new tab, etc. 

But files don't really behave like links—I think it would make more sense to use the default cursor.

See also: https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b

**Comment by jeremypw** [comment]
The use of different cursors in the view is because (a) depending on the click-mode setting a different thing could happen when you click (either activate/dnd or select) and (b) depending exactly where you are pointing a different thing could happen (and it is not immediately obvious). So the default (arrow) cursor is used when the item will be selected and the pointed (hand) cursor used for activation.  If we enforce a single click-mode then (a) goes away.   To make (b) go away requires ensuring sufficient other "affordance", I guess.  The main things to distinguish are (i) icons - click on the helper selects, click on the image activates (ii) list view - click on the filename column activates/dnd, click on other columns selects/rubberbands (iii) icon view - click-drag on image = dnd, click-drag on filename text = rubberband.

**Comment by jeremypw** [comment]
Closing needs to be re-raised (if necessary) in the current context of hybrid click mode.  The current version seems to only use the pointer for folders when "double-click to navigate" is off .
