### ISSUE TITLE
File manager cannot be opened with administrator privileges

### ISSUE THREAD

**Issue by Rahmsauce** [elementary/files#1419]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
The file manager cannot be opened with administrator privileges using the application menu or the command line.

### To Reproduce
From the applications menu:
1. Open the applications menu
2. Right-click on "Files"
3. Click on "Open new window as administrator"
4. Nothing happens

From the command line:
- `io.elementary.files` opens the file manager as expected without administrator privileges
- `sudo io.elementary.files` results in:
 `** (io.elementary.files:4293): WARNING **: 13:04:54.742: Application.vala:54: Running Files as root using sudo is not possible. Please use the command: io.elementary.files-pkexec [folder]`
- `sudo io.elementary.files-pkexec` responds with:
 `Unable to init server: Verbindung ist gescheitert: Verbindungsaufbau abgelehnt`
 (roughly translated to: `Unable to init server: connection failed: connection establishment rejected`) and:
 `(io.elementary.files:4583): Gtk-WARNING **: 13:10:48.834: cannot open display:`

### Expected behavior
The file manager should be able to start with administrator privileges.

## Platform Information

![platform_information](https://user-images.githubusercontent.com/53840228/89526485-1dc42600-d7e8-11ea-8122-598f785e24d7.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by jeremypw** [comment]
@Rahmsauce:  The command required is `io.elementary.files-pkexec` - you should not need to prefix it with `sudo`.  Does the correct command work?  Can you open as administrator using the context menu shown when you right-click on the Files icon in dock?

**Comment by jeremypw** [comment]
Are you logged in as a user with administrator rights?  If not, then using the context menus will not work.  It is perhaps a bug that the option is sensitive in this situation (or no dialog allowing entry of an administrator password appears).    Using the commandline as a standard user also does not seem to work although you are given the opportunity to run as another user so that appears to be a another bug (not sure if that is a Files issue though)

**Comment by Rahmsauce** [comment]
After typing the command without sudo, a popupappears requesting the administrator password, however entering the (correct) password results in the same response as typing the command with sudo. Right-clicking on the Files icon on the dock also does not work and the user I am logged into does have administrator rights.

**Comment by jeremypw** [comment]
Hmm, OK.  What happens if you run e.g. `synaptic` (a) with `pkexec synaptic` (b) `sudo synaptic` and (c) from the dock or application menu?  I find it works OK with (b) or (c) but fails with (a) even though I enter the correct password at the prompt.

However I find that `io.elementary.files-pkexec` is working on the commandline - although I have installed Files from the master source. So I am not sure what is going on here.

**Comment by jeremypw** [comment]
I notice your kernel version is quite a bit older than mine (mine is Linux 5.4.0-42-generic) not sure whether that is relevant.

**Comment by Rahmsauce** [comment]
On my system all three options seem to work fine. Perhaps, the old kernel is really the culprit since it is more than 2.5 years old. Also, I feel like I was the only person affected by #1368. Possibly, the kernel didn't get updated when upgrading to Hera as stated [here](https://elementaryos.stackexchange.com/questions/21374/kernel-version-is-still-4-15-after-upgrading-to-5-1-hera). I'm going to try updating the kernel and see if this fixes the problem.

**Comment by Rahmsauce** [comment]
I updated the Kernel to the same version as yours, however everything seems to work the same way as before. Nevertheless, thank you for pointing it out.

**Comment by jeremypw** [comment]
The latest Files stable release is 4.4.4 (use `io.elementary.files --version`) and there hasn't been any daily updates since then that are relevant.

Might be worth checking the policy file relating to Files at `/usr/share/polkit-1/actions/io.elementary-files.policy`.  Mine is:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN" "http://www.freedesktop.org/standards/PolicyKit/1.0/policyconfig.dtd">
<policyconfig>
  <vendor>elementary</vendor>
  <vendor_url>https://github.com/elementary/files</vendor_url>
  <icon_name>system-file-manager</icon_name>
  <action id="org.freedesktop.policykit.pkexec.io.elementary.files">
    <description>Run Pantheon Files as Administrator</description>
    <message>Authentication is required to run Files as Administrator</message>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/io.elementary.files</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>
</policyconfig>
```

Maybe try uninstalling Files and reinstalling?

**Comment by Rahmsauce** [comment]
On my system, Files seems to be a few versions behind (4.4.2). I tried reinstalling it using apt and AppCenter, however this didn't work, probably because I once installed Files using ninja (as described [here](https://github.com/elementary/files/blob/master/README.md)) and now I cannot find a simple way of uninstalling it. I also checked the policy file and it was exactly the same as yours.

Now, I am actually considering reinstalling the entire OS since I have been having a few other weird issues lately...

**Comment by jeremypw** [comment]
If you manually installed Files to `/usr/local` by mistake then it wont get uninstalled and will override the normal installs. Just delete any relevant folders and files under `/usr/local` if there are any.  Otherwise `sudo apt purge ...` will do a more thorough uninstall.

However, if you are sure to backup all your data and config files to another partition or device, it can sometimes to be quicker to reinstall than track down an obscure problem.

**Comment by stayinside4ever** [comment]
Hiya, possibly related - I was running the XAMPP (LAMPP) GUI version, clicked on "Open Application Folder", which I expected to launch Files and open the folder `/opt/lampp/htdocs`, but nothing happened and this appeared in the terminal:

```
** Message: 15:16:52.648: Application.vala:50: Report any issues/bugs you might find to https://github.com/elementary/files/issues

** (io.elementary.files:13053): WARNING **: 15:16:52.648: Application.vala:54: Running Files as root using sudo is not possible. Please use the command: io.elementary.files-pkexec [folder]

```

I assume it's because I have to run XAMPP as sudo, which is (probably) then trying to launch whatever file manager I have on my system. I also am guessing this would then extend further to any program that is run as sudo and trying to open Files...? Which is why I'm posting it here instead of somewhere XAMPP-related specifically.

**Comment by Rahmsauce** [comment]
@jeremypw I just reinstalled the OS and now everything seems to work fine. Thanks for your help!
