### ISSUE TITLE
Compressed file doesn't lose focus after extracting leading to two undesired selections

### ISSUE THREAD

**Issue by lazaroofarrill** [elementary/files#1505]
When i extract a compressed file in elementary both the compressed files and the extracted folder get selected. This is a very annoying behavior since if i instantly open the folder i extracted both the folder and the file get opened and i have to press esc to avoid this. I think this is not intuitive at all.

**Comment by jeremypw** [comment]
I am not sure whether the extracted files should be selected either.  I am not a great fan of automatically selecting files in general.

**Comment by lazaroofarrill** [comment]
> I am not sure whether the extracted files should be selected either. I am not a great fan of automatically selecting files in general.

I think your're right. That would allow you to keep your regular workflow if you just wanted the folder extracted and keep on with your work.

**Comment by jeremypw** [comment]
The problem is, Files core does not actually know which contractor has been activated.  The menu item is created by the contractor plugin.  The reason why the extracted files get selected is because __all__ newly created files are selected (a requested feature).  Likewise, if activating the file-roller contract were to deselect the target file, then __all__ contracts would have to behave the same (at least without some pretty horrible special case coding).

**Comment by lazaroofarrill** [comment]
I see. Well, at least last desktop update doesn't let you open when there are several items selected, that's a small improvement now you can't accidentally cause all those simultaneous executions.
