### ISSUE TITLE
Add typeahead search support

### ISSUE THREAD

**Issue by lazaroofarrill** [elementary/files#1506]
Files default type search behavior is kind of cumbersome performing a search and forcing you to press esc before being able to navigate to the file or folder you typed. If i wanted to run a search, which is something done less often than looking in the current directory, i think i would prefer using ctrl f

**Comment by jeremypw** [comment]
So your desired behaviour would be typing without pressing `<Ctrl>f` would just move the cursor/selection to the first file in the current directory with a filename starting with the typed letter?   Is there prior art for this?  Nautilus also requires pressing `Esc` to exit search mode.   

It seems there has to be some kind of "search mode" otherwise you would only be able to match a single letter because Files would not know whether a subsequent letter was a new search or a continuation of the current one.
If there is a search mode then you have to have a way of exiting it (e.g. by pressing `Esc`)

**Comment by lazaroofarrill** [comment]
> So your desired behaviour would be typing without pressing `<Ctrl>f` would just move the cursor/selection to the first file in the current directory with a filename starting with the typed letter? Is there prior art for this? Nautilus also requires pressing `Esc` to exit search mode.
> 
> It seems there has to be some kind of "search mode" otherwise you would only be able to match a single letter because Files would not know whether a subsequent letter was a new search or a continuation of the current one.
> If there is a search mode then you have to have a way of exiting it (e.g. by pressing `Esc`)

Well that used to be nautilus search behaviour in the past; It changed with gnome 3 (there's a nautilus fork that keeps this feature). Every other file explorer i've used like thunar, dolphin, caja shows this behaviour where you type a letter or the begginnig of the word and it selects the first file that matches that. Windows file explorer also behaves like this though is not as well implemented there.

**Comment by jeremypw** [comment]
>  Every other file explorer i've used like thunar, dolphin, caja shows this behaviour where you type a letter or the begginnig of the word and it selects the first file that matches that.

Files used to behave like that as well.  You had to press `<Ctrl>F` to enter a proper search mode (i.e. to be able to search for a string length > 1).  It was a design choice to change to the existing behaviour because matching a single letter to the start of a filename rarely finds the file you actually want.  We could probably make the current search mode smarter by prioritizing the display of first letter matches in the current folder before the full search completes and preselecting the first match in the current directory (which already moves the view cursor to the selected file).

**Comment by jeremypw** [comment]
>  ... forcing you to press esc before being able to navigate to the file or folder you typed. 

This is not so - you can navigate to the selected match file/folder directly from the Search bar by pressing `Enter`
