### ISSUE TITLE
Provide a Flatpak manifest

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1508]
See https://github.com/elementary/calculator/blob/master/io.elementary.calculator.yml as an example

**Comment by jeremypw** [comment]
I guess this will need a pretty porous sandbox :stuck_out_tongue: 

Nautilus uses
```
    "finish-args": [
        "--share=ipc", "--socket=x11",
        "--socket=wayland",
        "--talk-name=org.gnome.OnlineAccounts",
        "--talk-name=org.freedesktop.Tracker1",
        "--filesystem=host",
        "--talk-name=org.gtk.vfs", "--talk-name=org.gtk.vfs.*",
        "--talk-name=ca.desrt.dconf", "--env=DCONF_USER_CONFIG_DIR=.config/dconf"
    ],
```

But Dolphin has more restrictive access to the filesystem for some reason
```
    "finish-args": [ "--device=dri",
                     "--share=ipc",
                     "--share=network",
                     "--socket=x11",
                     "--socket=wayland",
                     "--filesystem=home",
                     "--filesystem=/run/media",
                     "--talk-name=org.kde.kiod5",
                     "--talk-name=org.kde.JobViewServer",
                     "--talk-name=org.kde.kpasswdserver",
                     "--system-talk-name=org.freedesktop.UDisks2" ],
```

**Comment by Marukesu** [comment]
I tend to prefer the dolphin implementation over nautilus here

**Comment by davidmhewitt** [comment]
> I tend to prefer the dolphin implementation over nautilus here

Yeah, well we don't really get a choice 😛

Dolphin's seems more restrictive because it uses the KIO bus. KIO is a daemon which essentially provides a file manager backend and Dolphin is just the user interface to that.

In theory, you can do that to some extent with gvfs, but I don't find it particularly weird that a file manager would ask for permissions to access the entire filesystem.

**Comment by Marukesu** [comment]
So the actual status of a files flatpak:

- Can't delete folders, but deleting files works.
- Can't open external apps

To build the manifest I need to make some changes on meson and services files:

- added a `portal` and `with-plank` options so we can skip building the filechooser and plank.
- renamed `io.elementary.files.services` to `io.elementary.files.db.services` because flatpak-builder fails because of the mismatching ids.
- renamed `io.elementary.files.Filemanager1.service` to `org.freedesktop.Filemanager1.service` because `flatpak install` fails because of the wrong service name.

**Comment by danrabbit** [comment]
I'm going to go ahead and close this since we need a native build to provide the file chooser portal and this just doesn't seem like a good candidate for Flatpak

**Comment by 12people** [comment]
Sounds like this issue was closed because Files does not make much sense as a Flatpak for elementary OS.

It might, however, be worth considering another use-case: using elementary Files on other distros, such as Fedora Silverblue. While Nautilus isn't bad by any means, elementary Files include Miller columns, which can be a huge productivity booster.

**Comment by jeremypw** [comment]
Probably needs someone to maintain a suitable fork on Flathub (and maybe a way of ensuring native installation on Elementary?)
