### ISSUE TITLE
Files showing drive AND volumes

### ISSUE THREAD

**Issue by pongloongyeat** [elementary/files#1606]
## What Happened

Files is showing the connected drive, it should only show volumes. Caused by #1596 

Before #1596:
![Screenshot from 2021-02-27 15-22-26](https://user-images.githubusercontent.com/31680656/109378718-c0243200-790f-11eb-92b1-a702ce8012ca.png)

After:
![Screenshot from 2021-02-27 15-18-58](https://user-images.githubusercontent.com/31680656/109378627-2492c180-790f-11eb-9cda-ee83b325303f.png)

## Expected Behavior

It should only show the volumes.

## Steps to Reproduce

1. Files daily.
2. Connect a drive.

## Platform Information
Files master

**Comment by pongloongyeat** [comment]
I do like that it shows the drive name though, perhaps in the future this could be a treeview? i.e. it shows that the volumes belong to the drive.

**Comment by pongloongyeat** [comment]
Seems this goes away after a Files restart

**Comment by jeremypw** [comment]
Yes, I had in mind making a drive an expandable item with its volumes as children. An unmounted drive needs to be shown but need to fix action when clicked.

**Comment by jeremypw** [comment]
See #496

**Comment by hanaral** [comment]
@jeremypw for the sake of simplicity it should probably just be left permenently expanded. The elementary sidebar expander style does not show its drop down arrow when not hovered - It would be pretty terrible experience for an average user who doesn't know what partitions are, let alone that their drive uses partitioning.

**Comment by jeremypw** [comment]
Tbh I would prefer for the arrow to be permanently visible even for the existing uses.  I think the unknowledgeable user would mainly use bookmarked locations.  They do not necessarily need to know what "drives" and "partitions" are - they are functionally equivalent to storage locations like the other sidebar items.  I was considering changing the "Devices" heading to "Storage" because of this.  Anyway need feedback from UX team as to whether they want to go down this route - it does rather complicate the code.
