### ISSUE TITLE
No indication you can search files

### ISSUE THREAD

**Issue by codygarver** [elementary/files#170]
There is nothing in Files' user interface that indicates you can actually search files. This can be a source of confusion for users, who will believe there is no such feature implemented.

Bounty: https://www.bountysource.com/issues/19860024-no-indication-you-can-search-files

**Comment by ypoz** [comment]
I propose adding a "gear menu" like the one in other apps to store advanced features. Then we can move the "show hidden files" (which doesn't belong in a context menu as it acts on all tabs) and the "refresh" (which is rarely useful other than as a trigger for procrastination) features into this menu and add a "lens" search button to the address bar in place of the former. It'll also serve as an additional extension point for plugins.

**Comment by jeremypw** [comment]
UX team have determined that any solution to this should not involve adding extra icons to the header bar.

**Comment by danrabbit** [comment]
Something we talked about the other day in Slack is showing the searchbar automatically when you're in the home directory. This would mean that the first time you open Files or when you open a new tab you see this affordance:

![bitmap](https://user-images.githubusercontent.com/7277719/39086637-9dceed1e-4549-11e8-93d7-a60c2c7f7bc5.png)

**Comment by waldyrious** [comment]
> Something we talked about the other day in Slack is showing the searchbar automatically when you're in the home directory.

Just to be clear, that isn't meant as a complete solution to this issue, right? I mean, what about when you're in another directory?

**Comment by SixFingeredAmish** [comment]
I think @danrabbit's suggestion regarding search on home folder makes sense

An additional affordance would be to change the Home icon (see below) into a Search icon upon hover
![](https://user-images.githubusercontent.com/3639540/44804169-95b25c00-ab8e-11e8-9673-a2a14945cb71.png)

**Comment by dtshudy** [comment]
What about a Search selection on the context menu?
![files-search](https://user-images.githubusercontent.com/7161587/45885529-af595480-bd84-11e8-85a5-39f7ddb3df1f.png)

**Comment by SixFingeredAmish** [comment]
@dtshudy I think the problem with that is that the option is hidden away an extra step. You need to go all the way to the home button, at which point you don't know what you can do. Then, you need to right click.

**Comment by dtshudy** [comment]
@SixFingeredAmish The right click menu is currently available on each of the breadcrumbs and knows the context.

**Comment by dtshudy** [comment]
Can anyone show me a good example of what Elementary considers a detailed design?

**Comment by cassidyjames** [comment]
Before this issue balloons out of control, I want to clearly define the scope: there is currently no indication that you can search in Files. I think the minimum-viable way forward that the design team agrees on is switching to a search entry in the Home folder. Since this is the default view in the app, shows up in new tabs, and shows up when tabs are closed, I think it sufficiently solves this issue in the simplest way.

For further search-related discussion, feel free to open issues with specific problems or solutions.

**Comment by peteruithoven** [comment]
I personally think that showing search bar interferes with the bread crumb interface. 

What about showing another action_icon? The tooltip for this button could be a a place to show the Ctrl + F keyboard shortcut. It could even be a place to explain that you can simply start typing to search. 
![search indicator](https://user-images.githubusercontent.com/523210/47380665-4146db00-d6fe-11e8-83f7-60d4c40c1853.png)

**Comment by jeremypw** [comment]
The native Gtk.Entry widget that the pathbar is based on can only show one action icon at the right so it would take some refactoring.

**Comment by megatux** [comment]
At least, I would like it to be included in the directory's context menu actions:
![dir context menu](https://user-images.githubusercontent.com/850020/49221361-a0f86c00-f3b7-11e8-9305-a4f37a2f19de.png)

**Comment by jeremypw** [comment]
@megatux : Best create a new issue about this as this one is closed.

**Comment by waldyrious** [comment]
@jeremypw while I agree that including an entry in the context menu for searching is outside the scope of this issue, I actually think its closure was premature, since the original issue was only partially addressed (the search hint is only visible when viewing the home folder, but not any other path).

IMO we should either reopen this issue, or make an explicit (and justified) decision not to support other paths. (I'd have guessed that a generic fix would be simpler to implement than one that applied to a specific location, but perhaps that's not the case.)

**Comment by megatux** [comment]
Sorry, didn't notice it was closed, because the resolution was pretty bad, IMHO. A special condition only displayed for $HOME but that works everywhere? :/ 
If we want people use Files to search, I think an action_icon is the best solution. If not, people will frustrate and start installing alternatives like Synapse.

**Comment by jeremypw** [comment]
This issue was 'fixed' in accordance with the views of the UX team. If other means of exposing the search capability are desired I think separate focused issues should be raised.
