### ISSUE TITLE
Highlighting all files in list view makes one file "accented"

### ISSUE THREAD

**Issue by Loreno10** [elementary/files#1704]
**OS: eOS 5.17**

Whenever I select all files in a folder (with a list view) I get something like this:

![image](https://user-images.githubusercontent.com/10273406/117866393-60df8800-b297-11eb-8944-0be0a680161d.png)

One of the files (I don't know why it's the fourth one in this case, I started dragging the mouse from the bottom to the top) is accented much more than the rest of them. I think it looks weird - all of the files should be highlighted in the same style.

**Comment by jeremypw** [comment]
The highlight represents where the "cursor" (keyboard focus) is. For rubberband selection it should be on the file you started the selection at, but it can be moved without losing the selection by holding the `<Control>` key down and pressing the up and down arrows.  There is an open issue (#473) for rethinking the styling and a related PR (#1176) but it has not had attention for a while.

**Comment by danrabbit** [comment]
Yeah this is intentional because it indicates keyboard focus. The convention is that things that are selected get a foreground color background and things that are focused get an accent color background. The focus style in elementary OS 6 is a lot less aggressive so it should feel more natural

Closing as "design conflict" since this is intentional
