### ISSUE TITLE
It is possible to scroll while renaming in ListView

### ISSUE THREAD

**Issue by eppixx** [elementary/files#1770]
## What Happened
While renaming files I found out, that it is possible to scroll with page up/down while renaming files. It results in a visual glich in which the renaming field stays in place, while the view scrolls.

## Expected Behavior
The fact that it is not possible to scroll with guestures while renaming suggests that the buttons should be disabled while renaming.

## Steps to Reproduce

1. Open Code and open a folder with enough items for scrolling
2. Rename a file
3. While renaming hit the scroll up or down button

## Platform Information
I'm using a updated Early Access version of ElementaryOS 6, but it is also possible on elementaryOS 5.

**Comment by jeremypw** [comment]
Hmm, yes - it does not happen in IconView but it does in ListView for some reason.

**Comment by jeremypw** [comment]
@eppixx  Just noticed your instructions to reproduce talk about Code not Files.  The issue does in fact also occur when renaming a file in Code's sidebar.  I am not sure which issue you meant to report but they both need fixing.

**Comment by eppixx** [comment]
That was a mistake on my part. But I'm glad it lead to the discovery of more bugs.

**Comment by jeremypw** [comment]
After further investigation it looks like this maybe an upstream bug in Gtk.TreeView because it also occurs in the Code & Music sidebars. Both Music and Code use a Granite SourceList which, like Files ListView uses a Gtk.TreeView under the covers.  

I have pushed a simple workaround for the Files issue, but cannot use this method for the other issues because Granite SourceList does not expose the TreeView or a signal to indicate rename is starting.  I'll have to file an issue against Granite.
