### ISSUE TITLE
Ctrl + D doesn't work

### ISSUE THREAD

**Issue by mathessaricci** [elementary/files#1786]
## What Happened
When you hit Ctrl+D to add some file or folder to bookmark it doesn't work.

## Steps to Reproduce

1. Select a file or folder
2. Press Ctrl+D

**Comment by jeremypw** [comment]
At the moment the `<Ctrl>D` shortcut adds the current tab location as a bookmark *not* the selected item.  If there is already a bookmark to that location then nothing will happen.  Not sure if this is the desired behaviour.  I guess it is to avoid adding large numbers of bookmarks accidentally if there is more than one selected (although it could be made to fail if there is more than one item selected).

I find that `<Ctrl>D` does work for adding the current tab location.

If you feel that it should add the selected item (if there is one) as a bookmark then I suggest you amend the issue title and description accordingly so that it can be discussed.

**Comment by jeremypw** [comment]
It is certainly incorrect that `<Ctrl>D` appears in the item context menu at the moment when it does not work on the selected item. It should only appear in the background context menu.

**Comment by mathessaricci** [comment]
Thanks @jeremypw I think I'll close this issue 'cause your #1788 is perfect to me.
