### ISSUE TITLE
Search is counterintuitive and inefficient

### ISSUE THREAD

**Issue by ibrahimrahman** [elementary/files#1806]
## What Happened

Searching for the a file/folder is incredibly inefficient as it is located at the very bottom of the list, which is filled with irrelevant entries. See screenshot:

![Screenshot-search](https://user-images.githubusercontent.com/5392273/130155419-fbfb9e2a-6bef-4ac1-b021-d18b7768fe88.png)

I just wanted to quickly navigate to the Github folder in my home directory.

## Expected Behavior

The search results from the current directory should be given the highest priority. 

What would really improve search is if the entries in the files window itself could be filtered. This would help with easier comparisons of/operations on the entries, especially when looking for multiple items with a similar name. As of now, the search funtion in Files is incredibly basic and leaves a lot to be desired, especially in comparison to Nautilus and other file managers

## Steps to Reproduce

1. Just search for something

## Platform Information

elementary OS 6 Odin

**Comment by jeremypw** [comment]
I think the "In this folder" category used to be at the top so this looks like a regression.  I agree that this category should be at the top.  Filtering the view is on the wishlist but is not trivial to implement.

**Comment by abodedis** [comment]
I haven't used search since the beginning as I was well aware of its limitations.  Thanks for reminding me that elementary OS has a file search :)

In the future, it could be useful to bundle elementary with a default File Search App.
Several nice ones exist that are capable of instantaneous performance (not including indexing time), like [FSearch](http://cboxdoerfer.github.io/fsearch/), among many others.

**Comment by jeremypw** [comment]
Any app that pre-indexes the files is going to easily outperform Files, which has to recursively search the current folder every time.  I would like some way of saving the current search results perhaps in a view, at least temporarily since at the moment the search results are lost as soon as you click on one of them.

**Comment by lazaroofarrill** [comment]
I'd love to at least have the option of disabling recursive search. Search is even worst than in Hera. Looking for files recursively is way less common than looking for the files in your current folder. Navigation that used to take no more than 4 seconds without even looking at my screen, now requires all my attention and to manually scroll through all my files, since waiting for a search result is not even an option.

**Comment by jeremypw** [comment]
I agree.  I have been intending to change things so that search results in "This Folder" are immediately available whether or not the recursive search is finished.  Just a question of finding the time.

**Comment by idovecer** [comment]
Also it will be good that keys like (up, down, home, end, enter) are functional for quicker browse in found items.

**Comment by jeremypw** [comment]
I think this should be converted to a discussion and then issues raised about more focussed issues/solutions.
