### ISSUE TITLE
HowTo Files Flatpak on Ubuntu Mate 18.04.5 ?

### ISSUE THREAD

**Issue by KDGNOR** [elementary/files#1825]
## Problem

install files with https://flatpak.elementary.io/repo/?? on Ubuntu Mate 18.04.5

## Proposal

first do: sudo add-apt-repository ppa:alexlarsson/flatpak
then do: sudo apt update
then do: sudo apt install flatpak
then do: flatpak remote-add --if-not-exists elementary https://flatpak.elementary.io/repo/?

## Prior Art

what right Repo name to add?

**Comment by danrabbit** [comment]
Files is not currently available as a Flatpak. You could try building from source but I imagine you'll have some trouble with library versions being unavailable on 18.04

Closing since there is no Files Flatpak

**Comment by KDGNOR** [comment]
Are going be released at all as flatpak with year?

**Comment by cassidyjames** [comment]
#1508 is already open and provides the status of packaging Files as a Flatpak. We don't immediately plan to package Files as a Flatpak on elementary OS itself due to sandboxing restrictions, though, as a file manager by definition needs to be able to manage all files, needs access to connected hardware devices, and provides the open file dialog for other apps.
