### ISSUE TITLE
Tools needed for the file manager!

### ISSUE THREAD

**Issue by aliceemanueli** [elementary/files#1836]
Suggestion for the system!

Hello good Morning!  Hope everything is going well out there!  I'd like you to read this message with your heart, I'm a longtime ElementaryOS user, and I'm having a hard time giving my opinions on some things I miss that could improve our end user experience.  You could by default the following option within the file manager when right-clicking on a connected USB drive "Format USB device?"  and "Restore disk image?"  .  So the system file manager itself would have the option to format flash-usb and also we would give the option to copy this Linux image into the file manager itself.  I think this idea is very cool!  Another idea would be for the system to notify you on the screen when a new device is connected.  not only by sound but also with a notification "New device connected" What should ElementaryOS do?" I think this would be great because we wouldn't need to resort to third party apps since the system itself has it natively and ready.   

thank you so much for listening to me!

**Comment by jeremypw** [comment]
@aliceemanueli Thanks for your suggestions! However, you should make a separate "feature request" issue for each separately so that they can each be tracked and commented on.  First you should search existing issues to make sure that a similar request has not already been made.

Formatting drives: already raised in issues #80 and #924.  This is a fairly specialised operation so we would prefer to hand this off to an external utility rather than write new code in Files. It would be nice to have a menu option on unformatted drives though that launched the utility.

Restoring disk image:  I assume you mean something like  "Startup Disk Creator" does?  I do not think an issue exists for this but there is the same argument against it as for formatting drives.

Notification for new drive connection: As this is something you would want to happen whether or not Files is running, this would need to be handled by a system background process rather than Files.  An issue exists here: https://github.com/elementary/triage/issues/49

**Comment by danrabbit** [comment]
As Jeremy pointed out, each issue report should be self contained and several of the listed things are duplicates. Going to go ahead and close this issue. Please feel free to open new non-duplicate issues reports for each individual issue or feature request :)
