### ISSUE TITLE
File Chooser Portal always spawns at 1,1 for maximized parents

### ISSUE THREAD

**Issue by danrabbit** [elementary/files#1845]
## What Happened

If the parent of the file portal is a maximized window, the portal window always spawns at 1,1  (top left)

## Expected Behavior

We should never spawn new windows at 1,1 and instead center the portal window on the display if we can't center it on the parent

## Steps to Reproduce

1. Maximize a window (like web)
2. Active the file chooser (like attaching a file in GitHub)
3. Notice that the portal is at 1,1

**Comment by jeremypw** [comment]
I find this only occurs on the "upper" display.  That is if there is one display it always occurs.  If there are two displays and one is above the other then it occurs on the top display but not the bottom one. If the position of the displays is switched then it still occurs on the top one.  It does not seem to be affected by which is the primary display.

I suspect this is not due to Files - there does not seem to be anything relevant in the portal code.  Perhaps @tintou can comment?
