### ISSUE TITLE
Cannot drag-and-drop files into folders on sidebar

### ISSUE THREAD

**Issue by kdwk** [elementary/files#1850]
### What Happened?

Unable to drag a file and drop it into one of the folders in the sidebar, including but not limited to Documents, Photos, and Trash

### Steps to Reproduce

1. Drag a file
2. Try to drop it into one of the folders in the sidebar

### Expected Behavior

The files are successfully dropped into the folder I hover over when dragging the files

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by pedropaulosuzuki** [comment]
Probably related to #1525.

**Comment by jeremypw** [comment]
Just tried this and could successfully move files between home subfolders using DnD.  Where are you moving files from? What permissions do you have for that file?  Are you seeing the "+" emblem when hovering over the sidebar folder indicating that DnD is possible? Can you perform the same move with cut and paste?.

I was using the latest master version, but I do not think any relevant changes have been made since Files version 6.0.3

**Comment by kdwk** [comment]
I see the + sign, but it’s for adding a bookmark in the sidebar. Basically, I can only add files to the sidebar as a bookmark

**Comment by jeremypw** [comment]
When the drop will create a bookmark, the adjacent rows move apart, a line appears showing where the bookmark will be placed and the emblem changes to "link".   When the emblem is "+" then the file should be copied or moved (depending whether on separate filesystem) to the bookmark underneath the hotspot of the cursor.  Is this not what you are seeing?

**Comment by kdwk** [comment]
Ah, I’m seeing that now.
However, that is very undiscoverable. You have to really squint at it to make out the little four-arrow sign under the cursor. I’ve already filed an issue report for the cursor.
Do you think something can be done in Files to make this a better experience? macOS (I don’t have macOS so I used iPadOS instead) flashes a highlight on the folder (giving a very noticeable visual indication) when a move to folder drag-and-drop action will succeed, like this:

https://user-images.githubusercontent.com/39268094/136185639-97222021-630b-4fcd-8ed9-2331be81422f.MP4

Do you think we can do something like this for Files on elementary OS? If so, I’ll open another feature request for this. 
Also, I’m not sure if anybody actually puts files on the sidebar as bookmarks. Would it be better if only folders are allowed on the sidebar?

**Comment by jeremypw** [comment]
I am marking this as "Invalid" and closing it because the issue described in the title does not exist.  New issue(s) need to be raised in the appropriate place(s) regarding the improved visibility of drop targets.   I have looked into the sidebar case and have a draft PR that adds another style class to the target listbox row.  However, I am not sure this should be necessary as Gtk should automatically highlight the target row so it may be a stylesheet issue.
