### ISSUE TITLE
Add select/deselect all to context menu

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#1903]
### Problem

Reading the massive thread at https://github.com/elementary/files/discussions/1729, I noticed a recurring theme of it being difficult for some to deselect items in certain views. At the same time, I realized Select All (Ctrl+A) action is not surfaced in the UI making it non-discoverable for anyone who doesn't already know the Ctrl+A shortcut.

### Proposal

We could encourage learnability for those using keyboards and usability for those who aren't by exposing "Select all" in the context menu of the view. I imagine these would make sense grouped in the menu with the existing clipboard actions of cut/copy/paste. If all the items are selected, it should change to "Deselect all".

### Prior Art (Optional)

We have a whole project board for [Keyboard Shortcut Discoverability](https://github.com/orgs/elementary/projects/32) with similar issues. :)

**Comment by jeremypw** [comment]
>  I imagine these would make sense grouped in the menu with the existing clipboard actions of cut/copy/paste

Cut/copy/paste only appears on the selected item(s) context menu, not on the background folder menu.  "Select all" is an action that affects the whole folder rather than the selected items so would be expected to appear in the background context menu.  Are you sure you want it on the selected item menu (or maybe on both)?

**Comment by cassidyjames** [comment]
My first instinct was just on the background of the view, but then that doesn't solve the deselect case where you can't click on the background, anyway—so yeah, probably both.

**Comment by jeremypw** [comment]
I have pushed a draft PR that puts a "Select All" action in the background menu (the other actions are not relevant since opening the background menu deselects all anyway).  It also puts a Select All or Unselect All action, as appropriate, in the selection menu together with an Invert Selection action.
