### ISSUE TITLE
Shorcuts stop working if cursor on sidebar/topbar

### ISSUE THREAD

**Issue by gorghino** [elementary/files#205]
If one/more files are selected (blued) BUT the cursor is in the sidebar, the keyboard shortcuts (e.g. Copy Paste and Delete tested) don't work because the files become grayed.
Actually if they're blued and you go up (Files Topbar or Pantheon topbar) files remain blued, but if you go to the sidebar and then to the topbar, they remain greyed.

**Comment by jeremypw** [comment]
This is because the sidebar grabs keyboard focus when hovered by the mouse so those shortcuts handled by the view will no longer work.  Shortcuts handled by the window, such as <Ctrl>Q continue to work.  Press the `Menu` key - the context menu appropriate to the widget hovered (sidebar or view) will show.

However, the pathbar does not grab focus until it is clicked on.  This is so the view can handle 'search on type' so you can search by just typing a search term without focussing the pathbar first.

Can you give any disadvantages in the current behaviour or any advantages in changing it?

**Comment by jeremypw** [comment]
I note that Thunar does not shift keyboard focus to either sidebar or view on hovering.  Is this behaviour preferable in your view?

**Comment by gorghino** [comment]
Actually yes, It happens (to me) that I select files, then I move to the folders on sidebar, CTRL+C, change folder, CTRL+V and I realize that nothing was previously copied. 
Or another scenario could be when you have two Files application opened, and you copy from the first, goes to the second but instead of catching focus on the view, you click on sidebar. You think you have the focus control, CTRL+V but nothing happens.

I don't actually fully understand why Files has greyed and blue selections. I mean, I expect grayed selection only if I'm out from hover Files. Don't you agree?

Even Windows Explorer behaviour doesn't lose the focus and I think it's not human friendly.

Btw, I can't find `Menu` key. You mean "Flag" key on keyboard or FN? It doesn't happen with me.

**Comment by jeremypw** [comment]
By `Menu` key I mean (on a UK keyboard) the key that is two to the right of the space bar, with a menu icon on it. 

I'll see if I can find out why Files was implemented that way.  I am just used to pressing Ctrl-C before moving out of the view and making sure I am pointing where I want to paste.

**Comment by jeremypw** [comment]
A branch that removes the focus-follows-mouse behaviour between the view and the sidebar has been submitted for consideration.
