### ISSUE TITLE
Inconsistent behaviour clicking on edge of row in List View

### ISSUE THREAD

**Issue by bambukouk** [elementary/files#2120]
### What Happened?

New version of Files (see https://blog.elementary.io/updates-for-november-2022/)
works in some areas but not in others...
![Screenshot from 2023-01-25 15 06 41](https://user-images.githubusercontent.com/50301871/214601481-d132544d-03d1-407b-8294-175939bd2e38.jpeg)

Having selected single click option:
![Screenshot from 2023-01-25 15 19 03](https://user-images.githubusercontent.com/50301871/214602195-1dca6234-07ad-4baa-94b5-00b4a9045d7f.jpeg)

I have observed that Bookmarks folders open with single click (as promised :+1: )
All the others require two clicks - one to select, another to open .

### Steps to Reproduce

1. open any folder in Bookmarks - single click works fine
2. try opening folders elsewhere - single click results in folder properties being displayed
3. second click is required to open selected folder in areas other than Bookmarks

### Expected Behavior

I would expect the behaviour (single click) should be the same for all the folders?

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
You can choose whether to select or open folders with a single click by right clicking on the background of the view.  As you show, there is an option "Select Folders with Single Click".  By default this should be "off" (unchecked) so that primary clicking on a folder a view will open that folder.

I have never seen the behaviour you describe where single-clicking on a folder opens the Properties window. This should only be possible by selecting the context menu item or using the shortcut `<Alt>Enter`.  I'll check the code to see whether there is any way single clicking could open this window.  Or do you mean the small property overlay at the bottom corner of the view?  This will appear whenever there are selected items.

Note that if any modifier key is down when you click, this will stop navigation and cause selection regardless of the setting. Also clicking on the selection helper will always select/deselect.

Also in ListView, you have to click in the Filename column in order to navigate.  Clicking in the Size, Type or Modified columns will select.

The behaviour aims to satisfy the requirements of both those who like single-click-navigate and those who prefer single-click-select when clicking on folders.

**Comment by bambukouk** [comment]
Maybe I am confused (easily done at my age :-1: )
I will try things as well,
in the meantime, this is what I am taking about:
![2023-01-25-13:37:45 002892001](https://user-images.githubusercontent.com/50301871/214615930-4cbeefc7-d085-4552-ae1d-ea248b7854a7.gif)

**Comment by bambukouk** [comment]
As promised, I did some more experiments and this is the result:
![diff](https://user-images.githubusercontent.com/50301871/214623939-8fe89847-1bb8-4218-a86b-bda0719f5566.jpg)

**Comment by jeremypw** [comment]
@bambukouk Thanks for experimenting! There was some debate about the best wording for the option - maybe we have to revisit it.  As it is the default option (how it should be after a clean install) is that the option is NOT ticked. Then you get navigation with single-click.  So the option is regarded as turning on something non-standard. The wording could perhaps be changed to "Double-click to navigate"? Would you have found that clearer?

You are right that that there is a small margin in each list row where the behaviour is not honored - that is a valid bug and we will look into fixing that - thanks.  I'll change the issue description appropriately.

**Comment by bambukouk** [comment]
@jeremypw All is clear now - and yes, I think current option selection was confusing (at least to me)
I personally tick ON what I select to use, so with current wording `Select Folders with Single Click`...
single click ON (tick) - use single click
single click OFF (not ticked) - anything else

or conversely, assuming that single click is default (as it should be :+1:  in my personal opinion)
the wording should be something like `enable double click alternative` to be ticked ON if selected.

Thank you for the confirmation of the bug.
I guess from my point of view this issue can be closed?
(BTW is there a link to the bug, so that I can track it?)

**Comment by danirabbit** [comment]
Hey @bambukouk here's the pull request that I proposed to change the label to "Double-click to navigate" https://github.com/elementary/files/pull/2107/files

**Comment by bambukouk** [comment]
@danirabbit thank you 👍

**Comment by bambukouk** [comment]
@danirabbit  and @jeremypw 
there are two elements to #2120:
1. double-clicking label (sorted out by #2107)
2. single click not behaving as it should in file list:
`... there is a small margin in each list row where the behaviour is not honored - that is a valid bug and we will look into fixing that - thanks`

number 2. remains outstanding, unless it has it's own/separate issue?

**Comment by bambukouk** [comment]
Working perfectly now :+1: 
Thank you
