### ISSUE TITLE
Remove double-click

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#222]
According to @jeremypw, it would simplify the codebase significantly. Files is designed for elementary OS, and in elementary OS, things are single-click. We've had it deprecated and non-configurable for a long time; I think it's time to remove it to clean things up.

**Comment by danrabbit** [comment]
Wogue made a super scientific poll for reference: https://plus.google.com/+WorldofGnomeOrg/posts/S57qPQ7puBE

**Comment by SubhadeepJasu** [comment]
I think I have a probable solution it would be nice if you take a look #227

**Comment by spheras** [comment]
Hi, to be honest, I love double click (and I hate single click) to open/execute files.  Maybe I'm old school user and it is a question of time using only single click.... but, sorry, that's my opinion.  Hope you don't remove that option :cry:

**Comment by donadigo** [comment]
Yes, removing the double click would make the codebase a little bit simpler, but I disagree that we actually should remove that feature, as it is used by people actively. If we really want to remove it, we should consider removing it now, and not releasing a new version of files until there is a new cleaner solution for this feature in the code, so that this option will stay there still for users.

**Comment by SubhadeepJasu** [comment]
A lot more people coming from the Windows desktop usually expect the same double click to open and single click to select feature. Its almost like after using an OS for such a long time that style of controlling stuff with mouse gets hard-coded in to our brains and its tough to get used to a new paradigm.

**Comment by SubhadeepJasu** [comment]
On that context, people are also used to press and hold controls especially in touch devices. Though this is not for touch only but the same feature could possibly be used to provide better control over single clicks system. I have an issue open for suggestions, I am all ears. Let's find a solution together.

**Comment by therocco** [comment]
Removing the code completely puts those users that might need it due to accessibility reasons out to pasture. Not all users are going to share your hand control of dexterity. Someone might suffer from a sort of hand tremor where they might accidentally click the mouse every now and again and do not want to accidentally open one or multiple files when that happens.

**Comment by SubhadeepJasu** [comment]
It would be best to have the option to switch between single click and double clicks in the mouse plug. This will satisfy all users. Specially the tremor victims.

**Comment by jeremypw** [comment]
The problem I have is the contradiction in having the code and maintaining it but making hard for users to access it.  It also inhibits working to improve single-click mode at the moment for fear of messing up double-click mode. Perhaps finding a way to separate out the double-click mouse handling into a separate optional plugin package (which could be maintained separately) is an acceptable compromise.  I haven't investigated the technicalities of that though.

**Comment by liqsquid00** [comment]
I think such decision should be made system-wide to ensure the consistency using the whole elementary OS. I'm not sure if the system relies on an unified API of controls and widgets. If it do relies on such API, it would be better to make this kind of changes there.

**Comment by jlnr** [comment]
My biggest gripe with single-click mode is that it is hard to find third-party apps which respect it. Even the Save Page dialog in stock Epiphany uses double-click mode (or maybe I broke my installation). I think a global switch in the Mouse plug might could to a more consistent experience for users who regularly leave the Pantheon stock apps.

**Comment by samlittler** [comment]
I'm happy with opening directories being single-click BUT in list view, if you right-click on anything apart from the text of a file's name but still in the area I'd call the file's row, right-click fails to select the file.

It's a minor gripe, but I feel single click would work much more smoothly if this was fixed.

**Comment by jeremypw** [comment]
I think this behaviour was implemented following complaints that it was hard to access the background menu in List View and particularly in Column View when the rows filled the window.  So right-clicking on white-space now behaves like right-clicking on the background.

There is a PR waiting to be reviewed and merged that will implement selection by long-press gesture that will make selection easier in ListView/single-click mode.

**Comment by eljefuri** [comment]
Fully agree with @spheras here. Single-click makes sense in nearly every other aspect of Elementary, with the exception of Files. With clicking being the primary UI interaction, an assumption is being made that the primary use of Files is opening things. With a bit more user testing I am pretty sure it would be found that the primary reason people use this tool at all is to _manipulate files_ e.g. move them, rename them, etc. Opening may be a less important case here, and if so I suspect it should be relegated to a double-click. This more closely mirrors macOS and at least older Windows behavior (I have not used Windows in a long time) and would cause less frustration. My own user testing confirms this, 15 friends-and-family laptops later.

**Comment by jeremypw** [comment]
Limiting Files to a single paradigm (either click to activate or click to select) will probably force equal numbers of users either to learn a new paradigm or to install a non-native file manager (probably the latter). It does seem a contradiction to me to create work supporting both paradigms but make it difficult for the user to chooser between them.  An AppMenu for Files has never met the approval of the UX team however.  One idea might be an 'official app tweaks' plug in switchboard.

I found getting used to the click-to-activate paradigm quite hard but am now used to clicking on the helper to select/deselect (or use the multi-select operations which can also select one file).

**Comment by jeremypw** [comment]
I would note that the Music app currently does *not* use a click-to-activate paradigm.  In List View a single click selects the item and a double click plays it.  So there are still some inconsistencies to deal with within elementary apps.

**Comment by naaando** [comment]
Hi everyone, want to give my two cents too, the click event is really messed up, but I don't think it's a matter of ripping off an important **feature** for users. Can't the click event be abstracted to some kind of "action" concept (primary action and select action) unifying both profiles?

**Comment by nobodywasishere** [comment]
I believe it should be, for at least miller columns, single click (including using the arrow keys) to open an enclosed folder in another column, and double click to launch a program/open a file. MacOS, of which elementaryOS is heavily based on, uses this, as well as single click to select, and double click to open. Single-click to launch also leads to a lot of misclicks and opening applications/files not intended to be. 

The end-user experience should come before simplicity of code, not to say code shouldnt be simplified or made easier to understand, but it should not come at the cost of the user experience.

**Comment by cassidyjames** [comment]
>MacOS, of which elementaryOS is heavily based on…

That's not remotely accurate. We never blindly copy macOS, and we prefer internal consistency and predictability over consistency with an entirely different platform. 

I am greatly in favor of cleaning up code and removing the **disabled by default and not GUI activatable**—and therefor untested—double-click behavior. Then we can refine how single-click works and how it works between different views. But coming in and cleaning up the code to better cater to the current default experience will provide a much better starting point than constantly trying to work around and trip over a hidden setting.

**Comment by nobodywasishere** [comment]
> That's not remotely accurate. We never blindly copy macOS, and we prefer internal consistency and predictability over consistency with an entirely different platform.
> 
> I am greatly in favor of cleaning up code and removing the **disabled by default and not GUI activatable**—and therefor untested—double-click behavior. Then we can refine how single-click works and how it works between different views. But coming in and cleaning up the code to better cater to the current default experience will provide a much better starting point than constantly trying to work around and trip over a hidden setting.

Fair enough on your first point, though you cannot deny the resemblance and inspiration, seeing as how macOS came first. I use pantheon-files on Manjaro so the Pantheon DE is completely foreign to me. I do agree we should go through and clean up the code, making it easier to work with, I think we should do so by making the double-click setting more integral to pantheon-files, making a GUI setting input, and simplifying the code surrounding it. This is one of the last GUI file managers with Miller Columns implemented and I would hate to leave due to losing double-click

**Comment by quequotion** [comment]
It took me a while to track down an active PR for this discussion: #1036 

I think some very good arguments were made in this discussion in support of keeping double-click for certain purposes (my favorite being @therocco's comment on accessibility). The "mixed mode" proposal may be a good compromise _if we're going insist on making anything in the file manager single click at all_.

The mixed mode compromise will be somewhat less jarring when users end up somewhere they don't expect upon unintentionally activating something as they'll only be one folder deeper than where they were before, *rather than in some program they didn't intend to open looking at some file they didn't intend to see*, or worse: waiting however long it takes for that too happen when the file is huge, on a network share, or the program is slow.

For what it's worth, I'd find mixed mode to be an acceptable default, but I'd like to keep a setting available to switch between "mixed mode" and "double click" (with "mixed mode" replacing "single click" entirely) and I think the most appropriate GUI location for that would be in [switchboard](https://github.com/elementary/switchboard-plug-mouse-touchpad/issues/78).

**Comment by danrabbit** [comment]
Closed in #1036

**Comment by m93a** [comment]
I'm trying to help my family (previously Windows users) to move to elementary OS and they find mixed mode weird and discouraging. In elementary 5, I could use the following command to re-enable double click:
```
gsettings set io.elementary.files.preferences single-click false
```
However, this option [seems to have disappeared](https://elementaryos.stackexchange.com/q/28079/19079) in elementary 6. Will there still be any way to re-enable double click in Odin?

**Comment by cassidyjames** [comment]
@m93a maintaining two completely different ways of interacting with the app was leading to complexity and issues, so the hybrid mixed mode is the way Files will work. It may take a bit of getting used to (as any OS that is different than Windows), but we think it offers the best compromise, Double-click still opens files, but it's faster to navigate around folders with a single click. There are no plans to revert this behavior.
