### ISSUE TITLE
regression: Files 6.5.0 does not remember window position

### ISSUE THREAD

**Issue by janxkoci** [elementary/files#2313]
### What Happened?

The last updates fixed many long standing issues, which is cool. But now the latest version does not remember window position after reopening it. AFAICT it's the only elementary app (aside from Appcenter) that does this.

### Steps to Reproduce

1. Open Files.
2. Move the window out of the center of the screen.
3. Close Files.
4. Open Files again - it's back in the center.

### Expected Behavior

Files should remember last window position before closing when reopening.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
This is part of GTK 4 and Wayland porting. Apps are unable to position themselves under Wayland, so the window positioning code here was dropped. There’s an open issue report against Gala to remember app positions instead: https://github.com/elementary/gala/issues/297

closing as “out of scope” since apps can’t position themselves under Wayland and there’s already an open issue report to handle this in the window manager
