### ISSUE TITLE
No large thumbnails

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#2455]
### Discussed in https://github.com/orgs/elementary/discussions/556

<div type='discussions-op-text'>

<sup>Originally posted by **doobes** August 17, 2024</sup>
Okay, this is decidedly sub-optimal:

![image](https://github.com/user-attachments/assets/e77c2290-26ea-4e75-887c-f862e83e8fb3)

Why is this displayed this way?

These images are 1500 x 1000 pixels.</div>

**Comment by jeremypw** [comment]
It looks like this is fixed in passing by #2340

**Comment by doobes** [comment]
Fixed?

![image](https://github.com/user-attachments/assets/96e62041-a828-4322-9c4e-4d78636bac25)

I'm on v7.1 latest version/update/upgrde.

**Comment by doobes** [comment]
'nuther folder:

![image](https://github.com/user-attachments/assets/dcff33ee-01f3-4c9f-9a3e-cf0aff48735b)

**Comment by doobes** [comment]
Ping

**Comment by doobes** [comment]
What does "completed" mean in this context?

**Comment by lenemter** [comment]
@doobes "completed" means that the fix was merged into the main branch and soon the fix will be automatically shipped to the Early Access. This ensures that the stable version doesn't have any severe regressions.

AFAIK Files is still compatible with OS 7 and you'll get the fix once we release a new stable version. There is no estimate for this yet so this might take a while.

**Comment by doobes** [comment]
Thank you
