### ISSUE TITLE
Cannot use search at all in Wayland session

### ISSUE THREAD

**Issue by teamcons** [elementary/files#2498]
### What Happened?

I am searching for a file.

I do Ctrl+F (because there is no search button it seems)
the path bar turns into search

i type the first letter, and get a search results dropdown.
Immediately the focus goes on the list. Ok but i want to continue typing to do a more precise search

i type the second letter - immediately a small search rectangle appears, focused, in which the second letter is in

As i write this report, i also notice the search results dropdown is a window, recognized by gala, and does not go away

![Uploading Bildschirmfoto von 2024-10-06 19.43.33.png…]()

### Steps to Reproduce

see above

### Expected Behavior

Just let me TYPE so i can search my shit

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment]
Confirm there is an issue with search when using "Wayland" session at the moment because of the way a separate floating window is used to display the results.  This does not work in Wayland. There is a PR in progress at the moment to fix this by moving to a Popover widget to display the results. See #2485.  Apologies for any inconvenience but that's the downside of using an Early Access version - it is a work in progress.

**Comment by teamcons** [comment]
> Apologies for any inconvenience but that's the downside of using an Early Access version - it is a work in progress. You might consider using a "Classic" session or a stable release for any serious work.

No need to apologize, it is on me. I am aware im using something unreleased (and do my part with the bug filing). Any frustration is not directed at any one contributor just lskfvhj if only everything magically worked
