### ISSUE TITLE
Coping or moving large files to external storage devices don't end after progress is 100%

### ISSUE THREAD

**Issue by SubhadeepJasu** [elementary/files#258]
Coping or moving large files to external storage devices don't end after progress is 100% and stays stuck there. I have to hit the cancel button to close the dialog box.

**Comment by cassidyjames** [comment]
I thought this is because the kernel or some other low level component is actually still syncing the file from memory to the device; I believe it's most noticable on especially slow external drives with especially large amounts of RAM.

Perhaps instead of just showing the progress as reported by the OS, Files could be smarter about this and show progress to ~99%, then show a different message while the OS performs the actual sync? I'm not sure what that would look lol.

**Comment by SubhadeepJasu** [comment]
I recently also found out that the copying may get stuck at some percentage completely, pressing cancel wouldn't work and the speed would remain fixed.

**Comment by SubhadeepJasu** [comment]
Would be good to show a sync progress because it feels like its stuck or crashed.

**Comment by jeremypw** [comment]
This sounds like a duplicate o #128
