### ISSUE TITLE
Remapped ALT + BackSpace to behave like DEL key not working 

### ISSUE THREAD

**Issue by b3n10** [elementary/files#315]
I don't have a <kbd>DEL</kbd> key on my laptop so I remapped <kbd>ALT</kbd>+<kbd>BackSpace</kbd> to do this. It is working correctly in Scratch or any other text editors like ViM but doesn't delete a file/folder in Pantheon File Manager.

Switching map to <kbd>Shift</kbd>+<kbd>BackSpace</kbd> works correctly (deletes text or file) on both text editor and Pantheon Files.

I installed Nautilus File Manager and <kbd>ALT</kbd>+<kbd>BackSpace</kbd> works as intended.

So the issue is only with <kbd>ALT</kbd>+<kbd>BackSpace</kbd> combination on Pantheon Files.

Also posted this on [unix stackexchange](https://unix.stackexchange.com/questions/421124/how-to-remap-alt-backspace-to-work-like-del-key)

**Comment by jeremypw** [comment]
I am not sure how you have done the remapping but I suspect what is happening is that  `Alt+BackSpace` is generating `Alt+Del` not `Del`.  The way Files is coded, it only responds to `Del` (to move to trash) or `Shift+Del` (to delete permanently).  It maybe that other apps ignore the `Alt`.  If it is considered that `Alt+Del` ought to be treated as `Del` rather than reserved for possible other uses then this simple to implement.

**Comment by b3n10** [comment]
@jeremypw 
here is <kbd>Shift</kbd>+<kbd>BackSpace</kbd> on my **/usr/share/X11/xkb/symbols/pc**

`key <BKSP> {  [ BackSpace, Delete ] };`

like what you said, it acts as 'delete permanently' because it doesn't go to trash

and for <kbd>ALT</kbd>+<kbd>BackSpace</kbd>:

```
key <BKSP> {
type= "PC_ALT_LEVEL2",
symbols[Group1]= [ BackSpace, Delete ]
};
```

Looks like Files has different behavior with <kbd>ALT</kbd>+<kbd>BackSpace</kbd> combination.

**Comment by jeremypw** [comment]
Do you have an `AltGr` key? If so, you could try mapping `AltGr + Backspace` to `Del`.  I do not think `AltGr` is detected as a modifier key by Gdk? So Files should treat `AltGr + Del` as `Del`.  Or find some other mapping that does not involve a modifier key as a workround.

I do not think there will be any more releases of Files for Loki now but this could be fixed in Juno by ignoring modifier keys other than Shift.

**Comment by b3n10** [comment]
@jeremypw 
No, I don't have <kbd>AltGr</kbd>

I also remapped <kbd>CTRL</kbd>+<kbd>BackSpace</kbd> (followed instructions [here](https://unix.stackexchange.com/questions/205226/xkb-make-ctrlbackspace-behave-as-delete)) and works correctly in text editors but still not in Files.

**Comment by jeremypw** [comment]
Files only recognises either no modifiers (for trashing) or Shift (for deleting) in combination with Del so Ctrl + BackSpace will suffer the same problem.
