### ISSUE TITLE
nextcloud/owncloud integration

### ISSUE THREAD

**Issue by georgKH** [elementary/files#345]
Similar to the dropbox-plugin, it would be fantastic to have these features for nextcloud/owncloud too.
The possibility to share files out of the right-click-menu would accelerate workflow.
Overlay icons would be a nice-to-have, but not that important to me.
https://docs.nextcloud.com/desktop/2.2/navigating.html#sharing-from-your-desktop
There seem to exist many owncloud client Plugins for several file-manager (nautilus, caja, dolphin, nemo), so some useful code could already exist:
https://help.nextcloud.com/t/install-nextcloud-client-for-opensuse-arch-linux-fedora-ubuntu-based-android-ios/13657

**Comment by jeremypw** [comment]
This was looked at a while ago and it was decided to wait for generic api that had been mooted to become available (rather than writing provider specific plugins). I understand that Gnome is still working on a generic cloud provider api but I am not sure it is ready to use yet.  Should a dev wish to contribute a suitable specific plugin in the mean time it would certainly be considered.

**Comment by danrabbit** [comment]
Closing in favor of #172
