### ISSUE TITLE
the drive color changes if it is almost full

### ISSUE THREAD

**Issue by torikulhabib** [elementary/files#350]
I hope the drive color changes if it is almost full
![screenshot from 2018-03-05 18 23 44](https://user-images.githubusercontent.com/26135527/36972741-d3187e16-20a2-11e8-8e28-391e94daf90b.png)

**Comment by jeremypw** [comment]
How would you define "almost full"?

**Comment by artemanufrij** [comment]
@jeremypw > 90% ?

**Comment by torikulhabib** [comment]
yes > 90% red color or another color.

**Comment by SixFingeredAmish** [comment]
I wonder what others think about this. Wouldn't this create more annoyance for users?

**Comment by arshubham** [comment]
I like the idea. However why change the color only when drive is almost full? Why not have different states with color at different levels? Such as, light green for (<20%), blue (<60%), orange (<90%) and red (>90%). I say this because the progress bar is quite small and difficult to guess approximately what % of drive is full. Even on windows where it has a large bar in width and height I have to see read the GB's remaining to fully guess how much drive is empty.  In elementary I am in the situations where I have to open the properties for the entire home directory on my small ssd.

**Comment by jeremypw** [comment]
Hovering the drive bookmark in the sidebar should give you the free GB in the tooltip, although for some reason the result is slightly different from that given by the directory property window.

**Comment by SixFingeredAmish** [comment]
I think just letting the user know that the drive isn't very helpful because most people don't know space management or what to erase.

But I agree it could be helpful to alert users, so I think this needs to be done in a helpful and empowering way, perhaps by having a storage utility of some sort identify large files so users can take some kind of action.

**Comment by CodingSpiderFox** [comment]
Added a PR that implements this

**Comment by CodingSpiderFox** [comment]
When >= 90%: 
![image](https://user-images.githubusercontent.com/25173078/84570769-da24e100-ad8f-11ea-93a5-835155c588d4.png)

When >= 75%:
![image](https://user-images.githubusercontent.com/25173078/84570790-f032a180-ad8f-11ea-947a-c97c7970da56.png)

**Comment by CodingSpiderFox** [comment]
PS: on my own fork I use a height of 5px so the bars are better visible
Also, I use alpha value of 1 so the colors look more beautiful
Third, I brought back the default blue color because I like it more.
![image](https://user-images.githubusercontent.com/25173078/84571126-a5b22480-ad91-11ea-9641-ab1d2d4904c5.png)

However, these changes are not part of the PR but you can find them here: https://github.com/CodingSpiderFox/files/tree/feature/bluediskusagebars
