### ISSUE TITLE
Selection badges show in column view as you navigate, regardless of selection

### ISSUE THREAD

**Issue by danirabbit** [elementary/files#468]
I haven't selected any directories, but I have two selection badges that make it look like I have

![screenshot from 2018-05-08 11 29 05 2x](https://user-images.githubusercontent.com/7277719/39775534-0960c180-52b3-11e8-8d80-ecd796af56bd.png)

**Comment by jeremypw** [comment]
This is analogous to list view - clicking on "expand" makes the parent folder appear selected.

This is a consequence of, in Gtk.TreeView which both views are based on, the item under the cursor or is activated is automatically selected.

**Comment by jeremypw** [comment]
I notice that Nautilus does not have this behaviour so I guess it is an issue.

**Comment by jeremypw** [comment]
This is linked to the native widgets automatically selecting the item under the cursor.  This is so that keyboard users can just move the cursor onto an item and then copy it with Ctrl-C.

Do you mean that the item in the parent folder should become deselected when has been activated?   What should happen in the child folder when the focus moves back to parent?

There are quite a few issues that need clarifying here.

**Comment by jeremypw** [comment]
Closing this as Column will be completely rewritten with new widgets in the upcoming Gtk4 version.  A new issue should be raised if the new version has issues.
