### ISSUE TITLE
Make file picker "sorting" consistent with the Files app

### ISSUE THREAD

**Issue by uncertainquark** [elementary/files#470]
File picker doesn't show folders before files by default, which is the way the default sorting in done in the Files app. The sorting behavior should be consistent across the main app and the picker.
![screenshot from 2018-05-09 11-20-59](https://user-images.githubusercontent.com/22585732/39798154-ea53585a-537c-11e8-9b97-1d393e41132c.png)

If you right-click however, the option to sort folders before files becomes available.

![screenshot from 2018-05-09 11-21-33](https://user-images.githubusercontent.com/22585732/39798170-fea79ff0-537c-11e8-9656-ffdae6e6b2b0.png)
  
![screenshot from 2018-05-09 11-21-43](https://user-images.githubusercontent.com/22585732/39798183-0b05fbf2-537d-11e8-9631-d5ee37f96cae.png)

This bug is similar to #451 where the file picker and the main app are not consistent.

**Comment by jeremypw** [comment]
See PR #449.  This, if accepted, would make both the filepicker and main app honor the same setting.

The sidebar issue is more problematic as I do not think there is a setting for that.  I doubt UX team would want to follow GtkFileChooser sidebar for the main app so we would have customise the sidebar in the FileChooser which is not easy.   However, I believe that in future there will be a way of completely replacing the FileChooser rather than customising the Gtk one.

**Comment by jeremypw** [comment]
PR #449 now merged so closing this.
