### ISSUE TITLE
Error message dialog on Filechooser dialog

### ISSUE THREAD

**Issue by arshubham** [elementary/files#536]
It only happens the very first time after a fresh install and never saw anytime since. Might be solved when these issues are solved https://github.com/elementary/files/issues/129 and https://github.com/elementary/files/issues/403 . However till then maybe there is a way to suppress this. The dialog functions normally after dismissing the message.
![screenshot from 2018-07-05 20-25-42](https://user-images.githubusercontent.com/14235191/42356914-cf17b0b0-80f2-11e8-8240-653b8d0d7a88.png)

**Comment by jeremypw** [comment]
What actually is  the location you are trying to open and do you have the necessary permissions? It appears to be on a mounted drive?  Which app launched the filechooser?  Or did it just appear spontaneously?

**Comment by arshubham** [comment]
No particular location. It only happens once on **fresh install** on opening file chooser from any app with capability. In the image I clicked _open a file_ in **code**. The error dialog is shown **only the first time.**

**Comment by jeremypw** [comment]
It appear the file chooser is trying to show `/home/shubhamamora/Desktop`?.  As your elementary home directory after  fresh install should not contain a "Desktop" folder  (and presumably does not) this would explain an error message being shown.  I suspect this is because Files asks the Gtk.FileChooser to show the "last-folder-uri" setting from the io.elementary.files.file-chooser schema on opening the file-chooser without checking its accessibility. This setting should default to an empty string.  Perhaps in that case Files should use e.g. the local user home directory rather than letting the Gtk.FileChooser deal with it.

**Comment by jeremypw** [comment]
I have experimented with a fresh install and can confirm that this is associated with the default value of '' for "last-folder-uri" setting.
