### ISSUE TITLE
load .iso icon

### ISSUE THREAD

**Issue by torikulhabib** [elementary/files#560]
load .iso not show icon CD but show icon drive but on root icon 
![vb](https://user-images.githubusercontent.com/26135527/43051589-5db66a04-8e46-11e8-978b-5eb28a406be1.png)

**Comment by jeremypw** [comment]
Is the .iso on a physical CD?

**Comment by torikulhabib** [comment]
right run on root and elemntary.iso its show icon CD

**Comment by jeremypw** [comment]
For me using a physical CD the entry in the side shows the CD icon when mounted when running both as ordinary user and as administrator. (however when unmounted it appears as an ordinary user but not as root. Root is inhibited from mounting external devices.)

Either this bug is unconfirmed, fixed in current master version, or I have misunderstood.

**Comment by jeremypw** [comment]
Closing as unconfirmed for several years.
