### ISSUE TITLE
there is an issue on laptop screen closing

### ISSUE THREAD

**Issue by mahmodlte** [elementary/files#613]
Dear Elementary Developers Team,

there is an issue on laptop screen closing when i close the screen it is not going to sleep or suspend mode it is still working and some day i put my laptop on the bag and i found that it is still working and becomes very hot i hope to fix soon 

Thanks 
Mahmood

**Comment by ryonakano** [comment]
@mahmodlte I think you should close this issue and submit your issue to an appropriate repository like https://github.com/elementary/switchboard-plug-power, because your issue seems to be related to power management and this repository is not for it but is for Files, the file manager of elementary OS.

**Comment by danrabbit** [comment]
Closing at "Out of Scope" since Files is not in control of power management tasks
