### ISSUE TITLE
Breadcrumbs sometimes incorrect at startup

### ISSUE THREAD

**Issue by jeremypw** [elementary/files#761]
* Arrange for two tabs to be restored, one showing a folder that is slow to load (e,g. large number of files) and one that is quick to load.  Make the quick one the second tab and make it active when Files is closed.

* Re-open Files.  The breadcrumbs will show the the path of the slow folder even though it is not the active tab.

This is because the 'done_loading' signal from the slow folder is causing the pathbar to update even though it is coming from a slot that is no longer active.

**Comment by jeremypw** [comment]
Example:

![screenshot from 2018-11-16 18 09 19](https://user-images.githubusercontent.com/10513844/48639215-da4dd680-e9ca-11e8-877c-2348775f871e.png)

**Comment by KomalleanaByzantis** [comment]
I have managed to reproduce this error in the following two examples. I hope that this report will be useful.

---

# Prerequisites
- [x] I have searched open and closed issues for duplicates.

# Describe the error

The error has already been described.

## To reproduce

Test case 1:
1. Open Files.
2. Open another folder in a separate tab.
3. Close and reopen Files.
4. The address bar indicates the address of the Home folder; i.e. an empty address with a search icon.

Test case 2:
1. Open Files.
2. Open the File System in a separate tab.
3. Click the tab of the Home folder.
4. Close and reopen Files.
5. The address bar indicates the address of the file system.

## Expected behaviour

The correct path in the address bar is displayed.

## Screenshots or screen recordings

[Screen recording](https://github.com/elementary/files/files/4140711/Incorrect.path.displayed.in.the.address.bar.when.starting.the.application.zip)

# Platform information

![System information](https://user-images.githubusercontent.com/51057001/73562303-231c6e80-445b-11ea-8e4e-cb8d6faeea6c.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

Language: French
Keyboard: English (US) - English (Dvorak intl., with dead keys)
Location: Paris

The testing system is installed on a small partition on a ThinkPad T470 laptop on which UEFI Secure Boot is disabled. Aside from specifying the language, keyboard, location, initial user, and the specific partition in which to install elementary OS, all of the default settings were used during the installation. No Internet connection was used during the installation. The only system-wide changes which have been made after the installation are that the system connects to the Internet by wi-fi via a Linksys WRT54GL Wireless Router and that [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder/) has been installed via AppCentre.

# Additional context

Before this test was performed, the following steps were followed:

1. All system-wide changes from previous tests were reverted.
2. All system components were updated via the blue “Update All” button in AppCentre.
3. A new administrator user named “Essai” or “Essai 2” was created with the password “komalleana”.
4. The current user was logged out and the new user was logged in.
5. The old user was deleted, the screen resolution was set to 800x600 at 60 Hz, tap clicking was disabled, and the touchpad pointer speed was set to the maximal value.
6. The computer was rebooted.
6. The test user was logged in.

**Comment by jeremypw** [comment]
I did produce a PR to fix this known issue but it did not attract any review/approval perhaps because it was a little involved.  I did intend to try to simplify the fix but have not yet got round to doing so.
