### ISSUE TITLE
Files doesn't respect "Event Sounds" option in Settings

### ISSUE THREAD

**Issue by aaronraimist** [elementary/files#766]
Files doesn't seem to respect the "Event Sounds" option in the Elementary OS Settings. The delete file sound still plays when that option is disabled.

See https://elementaryos.stackexchange.com/questions/17040/how-can-i-disable-sound-effect-of-deleting-files-in-elementary-os-5/17042

**Comment by megatux** [comment]
Not Files, not notifications, volume changes, etc. [switchboard-plug-sound issue](https://github.com/elementary/switchboard-plug-sound/issues/88)

**Comment by danrabbit** [comment]
Marking this as "Needs Design" since it's unclear that this is the intended use of that setting.

**Comment by jeremypw** [comment]
Inasmuch as elementary does support user control over whether or not certain sounds are heard as a recent of certain actions, it seems reasonable that Files should have a way of turning off its own sounds.  Rather than having its own setting and UI to do this, it is simpler just to follow the global setting.

**Comment by peteruithoven** [comment]
Looks like the intentions of the setting was to control just event alerts, see: https://github.com/elementary/switchboard-plug-sound/issues/107#issuecomment-510193956
So this issue was invalid...
