### ISSUE TITLE
Left click, a single click behaves like a double click

### ISSUE THREAD

**Issue by dackdel** [elementary/files#773]
When my mouse is connected and also when its just on my trackpad. Running Juno on a Razer Blade 2017 non-touchscreen laptop.

**Comment by aleksandar-stefanovic** [comment]
This is intended behavior. If you want to select items, you can click on the "tick" icon that appears on hover, or you can hold Ctrl key and select the items you want.

**Comment by dackdel** [comment]
Is there a way to toggle this behaviour?

**Comment by aleksandar-stefanovic** [comment]
I encourage you to try single click, but if you really want to enable double-click behavior, you can execute:

`dconf write /io/elementary/files/preferences/single-click false`

**Comment by aleksandar-stefanovic** [comment]
I think you should look into [Accessible configuration](https://elementary.io/docs/human-interface-guidelines#accessible-configuration) paragraph of the HIG, it might be an interesting read.

**Comment by dackdel** [comment]
Glanced through, will read it fully but i think i get the general idea. A single click as double click for a folder maybe is okay but definitely not for a file because dragging and dropping a file or set of files from folders to external hd or vice versa is such a daily task for me and I prefer a gui+mouse to do these moves. I need to be able to select multiple files with ease(my already existing mental model of clicks). Mac user here for like 2398years and switched briefly to windows(razer blade) to stay on warranty and now finally my first real non-mac/windows experience. I want eos to be the solution. Its great so far, im finding few strong faults. I really miss the clutter of files on my desktop as well apart from click issues.

**Comment by eljefuri** [comment]
Completely agree with you here @dackdel . Coming from macOS with its stable and gloriously forgiving Finder (⌘Z to undo any action, where are thee), I find Files almost unusable in its attempt to force this universal single-click paradigm where it clearly does not belong. To make matters worse, [trackpad instability](https://github.com/elementary/os/issues/157) renders the whole experience all the more terrifying: I have now given over 20 Elementary laptops away in order to observe behavior. Users of all kinds, _but especially trackpad users_, are constantly opening files accidentally and generally share a dread around the Files app.

Let's call a spade a spade: There are some terrible design decisions here. Double-click to open a file has been standard on our systems since 1984, and goes back even further than that. The developers come from a late Windows background and probably missed the pleasure of using a Mac. As I have said elsewhere, we should be inheriting the best user experience guidelines from Apple (who has spent countless millions -- _if not billions_ -- on research over the years), not ignoring them.

**Comment by dackdel** [comment]
I wish the devs and founders would reply to the above comment ^ especially about it being an ego project. Its as if the eOS team does not use a mouse at all to drag and drop files. They live in the terminal and assume their users do too.

**Comment by aleksandar-stefanovic** [comment]
> They live in the terminal and assume their users do too.

That's simply a prejudice and is not true.

**Comment by jeremypw** [comment]
Files does already support single-click select so the only issues are
1)  what is default (need to change view of UX team)
2) whether to expose that setting in the interface  (also need to change view of UX team). 

App devs cannot override the UX team in these matters.

**Comment by jeremypw** [comment]
It may be worth considering what would ameliorate the objections to single-click activate. E.g. larger helper target when file item is hovered.  Or select on long press.   

Holding down the Ctrl while clicking stops the file being activated.

**Comment by jeremypw** [comment]
A recent commit stops single-click activate when multiple files are selected and one of them is clicked, but still unselects existing selected files if an unselected file is selected.  There has been some talk of entering a "select mode" when at least one file is selected.

**Comment by Akryum** [comment]
I also agree the single-click choice needs to be reconsidered. Even after years using eOS, it still happens to me to open a file by mistake, especially when using a touch pad. And selecting multiple files or dragging them has never been an easy and intuitive task.
