### ISSUE TITLE
Can't set desktop background as photo in files

### ISSUE THREAD

**Issue by rugglcon** [elementary/files#807]
When I have a Files instance open and I right click on a photo and then click 'Set as Desktop Background', my background does not get set. The images I've tested on are in `jpg` format, so not sure if that is the issue. I'm on elementary OS 5.0 Juno with all latest updates installed.

Edit: a little update on this, changing the background like that does change the picture that is displayed on the lock screen, but not the general desktop background.

**Comment by jeremypw** [comment]
I am not experiencing this - I successfully set a range of pictures in different formats as desktop background.

This function is performed by a contractor outside of Files so unless all contractors are not working it is unlikely to be a Files bug.  Sounds like either you have something installed that is overriding this setting or the picture you have chosen does not meet some requirement for a desktop background.

Look in ~/.local/.share/backgrounds to see whether your chosen picture has been copied there.

Using dconf-editor or otherwise search your gsettings for "background" keyword to see whether there is another setting taking precedence.

**Comment by jeremypw** [comment]
Does setting the background using the Settings app (Switchboard) work as expected?

**Comment by rugglcon** [comment]
So yes and no, it stops and starts working unexpectedly, both via command line and with the Files app and with Switchboard.

**Comment by rugglcon** [comment]
Okay last addition: I copy the file to ~/.local/share/background manually and then try and set the background via command line, doesn't work. HOWEVER the file then shows up in Switchboard -> Desktop, and when I click it there it sets the background correctly and the lock screen. The command line seems to be really hit or miss. So long story short, this seems to be a gnome desktop issue and not strictly a Files issue

**Comment by jeremypw** [comment]
OK thanks. I'll close this as "Out of Scope" for now.  Please feel free to reopen if you identify it as a specifically Files issue.

**Comment by rugglcon** [comment]
@jeremypw I don't want to reopen this issue, but I think I found how to reproduce the problem. On my laptop, after a restart I'm able to set my desktop background as many times as I want just fine. However, if I put it to sleep a few times and wake it up from sleep, then I'm no longer able to set the background. I'm not sure where to report this issue. Please advise

**Comment by cassidyjames** [comment]
@rugglcon it sounds like it might be this issue? https://github.com/elementary/gala/issues/13

**Comment by rugglcon** [comment]
@cassidyjames that is in fact my issue. if i restart the gala process my background changes to the selected image and i can change the background a few more times before it stops working again.
