### ISSUE TITLE
Remember per folder view mode

### ISSUE THREAD

**Issue by sprite-1** [elementary/files#821]
I searched for "per folder view" on the issues and this didn't seem to pop up.

Basically, it would be great if Files remembered the last used view for the folders. For example, I don't necessarily prefer the Grid View when I'm browsing a folder that has nothing but text files.

**Comment by jeremypw** [comment]
Another use case would be to switch to ListView for very large folders as IconView becomes unusable slow for 10,000s of files.

There used to be automatic switching to IconView for folders with "icon" in the path but that was taken out as the app should not presume to know the users wishes in this way.

I guess for filesystems that support file metadata this could be implemented in the same way as per folder sort order is now.  

Not sure this will meet @elementary/ux  approval though.

**Comment by cassidyjames** [comment]
@jeremypw I would not switch the view automatically based on the contents, but remembering the view per folder could be good. The main concern/interaction I'd want to sort out is how we determine the view. If I select Columns in home and then navigate folder-by-folder to ~/Pictures/2018/12/21/, do each of those folders get the Column view flag set? If I navigate straight to ~/Pictures/2018/12/ later from the location bar or opening from another app, what view do I get? If I change the view in this folder to icons, what happens when I'm in the Column view later and navigate back to this folder?

I guess my main concern is that the view is a bit different than just a sort order, as the view affects navigation across multiple folders instead of just the presentation _within_ a single folder.

**Comment by jeremypw** [comment]
In Miller view (columns), the folders would have to ignore the per folder setting - there is a special AbstractDirectoryView type for this view.  So I would say it is neither read not set in this view.

**Comment by sprite-1** [comment]
> The main concern/interaction I'd want to sort out is how we determine the view. If I select Columns in home and then navigate folder-by-folder to ~/Pictures/2018/12/21/, do each of those folders get the Column view flag set? If I navigate straight to ~/Pictures/2018/12/ later from the location bar or opening from another app, what view do I get? If I change the view in this folder to icons, what happens when I'm in the Column view later and navigate back to this folder?

In Windows' Explorer, if you deviate from the default view, they create a hidden `desktop.ini` file to store the view that a folder should follow. Then the subfolders adhere to that from that point onward. If you wanted to have the folder (and subfolders) follow the "default" system view, you had to delete that file. And the other `desktop.ini` that may be inside the subfolders, etc. Then again, I don't know if I would want that same approach on eOS.

**Comment by jeremypw** [comment]
Going to close this as "Design conflict" as there are unwanted side effects of automatically changing view mode based on folder location or content.
