### ISSUE TITLE
Open compressed files as folders in the file manager

### ISSUE THREAD

**Issue by aggalex** [elementary/files#83]
File-Roller has been and is working good on elementary OS, but it is a little off to the appearance off the apps in elementary OS. The header-bar for example has symbolic icons, the app has a menu under the header bar, etc. Building, however, a new archive manager is quite a tedious task. Thus, I suggest opening supported formats from compressed folders as simple folders, just like windows explorer does with *.zip file.

**Comment by jeremypw** [comment]
Files uses gvfs so it would be possible to handle archive files using the gvfs back-end. They would be read only due to current limitations in the gvfs back-end. You could still read and copy the component files however. Files already provides, via contracts, facilities to extract archives and compress file selections within the Files UI and it would not be desired to provide extensive functions to handle compressed files within Files itself.

**Comment by danrabbit** [comment]
Consensus from UX team is this is probably not a good idea. It adds a new type of view with all of its own new special cases that will cause confusion since an archive isn't a folder and won't act like a folder. This seems to fall under the "kitchen sink"/feature creep. File Roller is always going to provide a better dedicated archive management experience than what we can cram into Files. If you want to browse the archive with Files then I think the course of action is to extract it so that it becomes a folder.

Closing as "Won't Fix".
