### ISSUE TITLE
Cannot rename file while downloading

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/files#87]
Hi.
It seems that if you are trying to rename a file with F2 in the same directory where there is active downloading, files will exit edit operation every few seconds. It feels like refreshing is causing this, not sure.

**Comment by jeremypw** [comment]
Renaming is currently exited whenever the editable widget loses keyboard focus - which it does when the progress widget is displayed as it is a modal dialog.  There are plans to refactor the progress display and this issue will have to be taken into account.

**Comment by jeremypw** [comment]
Or did you mean downloading from external source? In which case you are probably right that it is the view updating that causes the rename to lose focus and end.  It may be possible to block the view updating if there is a rename in progress.

**Comment by WebShapedBiz** [comment]
Thank Jeremy for your answer.

You guessed right, I was referring to downloading from browser for example.
When having a progress widget (that should be a complete new set of bug
reports regarding that one) one does not tend to poke around but wait the
operation to end. On the other hand, when there is something downloading
from web or torrent that could take a while, nobody wait.

Cheers,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-24 17:37 GMT+02:00 Jeremy Wootten <notifications@github.com>:

**Comment by jeremypw** [comment]
I have investigated a bit and found that it is problematic to allow renaming to continue while updating the view with new downloaded files because Gtk does not expect the TreePath to the item being renamed to change, which it can do if the one or more downloaded files precede it in sort order.  In that case the new name is applied to the wrong file!  The only alternative is to stop the view updating at all while the rename is in progress, which could be confusing if you are expecting to see new files appearing as they download.  I think this is a bit of a corner case and I am not sure what the best solution is (or if it is worth fixing tbh)

**Comment by WebShapedBiz** [comment]
Thanx Jeremy.

Better leave it, complicated solutions are better to left aside.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-24 19:09 GMT+02:00 Jeremy Wootten <notifications@github.com>:

**Comment by jeremypw** [comment]
OK, I'll mark it "Won't Fix" then.  Thanks for the report anyway.

**Comment by jeremypw** [comment]
A workaround is to move the file out of the Download directory before renaming.

**Comment by WebShapedBiz** [comment]
Got it. Thank you for your time and effort Jeremy.

Best regards,

Sinisa Perovic
WebShaped.biz

Web: http://www.webshaped.biz
E-Mail: sinisaperovic@webshaped.biz
SkypeID: sinisaperovic
Telegram: @sinisaperovic

2017-07-24 19:20 GMT+02:00 Jeremy Wootten <notifications@github.com>:
