### ISSUE TITLE
UX Proposal: Files looks like this with systemwide `developer mode` switch.

### ISSUE THREAD

**Issue by dkotrada** [elementary/files#876]
**I would like to propose an improvement for a specific user type of elementary os.**

### For Developer User

- improve right click menu of Files. Drop slide out of "Open in Terminal" "Create New File" "Create New Folder" and replace it with just Icons.

- Eliminate other "Slideouts"

- integrate git awareness into Files. Interesting Idea here: https://gitlab.gnome.org/GNOME/nautilus/issues/586

- Developer mode can be turned on like in Android in Switchboard

- Other features that improve the UX of a developer on Elementary OS.

Please share your thoughts.

**Comment by cassidyjames** [comment]
@dkotrada thanks for filing an issue.

>- improve right click menu of Files. Drop slide out of "Open in Terminal" "Create New File" "Create New Folder" and replace it with just Icons.
>- Eliminate other "Slideouts"

We generally avoid configuration, especially something that could seem unrelated like a "developer mode" and changes to the user interface in a specific app. See the [Accessible Configuration section of the Human Interface Guidelines](https://elementary.io/docs/human-interface-guidelines#accessible-configuration) for more on this topic. In this case, I don't think these changes would be for accessibility reasons, and frankly I don't see how some of them are any better for "developers"—it feels like it's more of a concept of "power user," which is not in itself rationale for changing the UI.

>- integrate git awareness into Files. Interesting Idea here: https://gitlab.gnome.org/GNOME/nautilus/issues/586

I thought this had already been filed here. Huh. I've separated it out into #877.

>- Developer mode can be turned on like in Android in Switchboard
>- Other features that improve the UX of a developer on [e]lementary OS.

These are outside the scope of Files since they don't currently exist and aren't really specific. What would the wider purpose of a "developer mode" switch be? What would it actually change? How would those changes actually improve the experience for developers?

**Comment by dkotrada** [comment]
Agree with configuration. I've read guidelines. But forgot it.
- Open Terminal here 
- New File here
- New Folder here

If I need to repeat them again and again then they are to deeply nested in Context Menü of Files.

Compare 
- Rightclick -> Mouse movement -> Terminal Icon
and
- Rightclick -> Mouse movement -> Open in -> Mouse movement

This can all be done in an editor or in terminal directly. But would be nice in Files too.

**Comment by janxkoci** [comment]
Note that you can use keyboard shortcut Ctrl+Shift+N to create new folder.
