### ISSUE TITLE
Integrate Git status

### ISSUE THREAD

**Issue by cassidyjames** [elementary/files#877]
I could have sworn we had this filed somewhere but didn't find it. Since Files is a more advanced workflow (as it deals with files directly versus "content" via the default content apps), I wonder if it would make sense to integrate Git awareness and status into Files. This could be super handy for managing repos with a lot of assets to see a visual indication of status, especially when the contents of the repo aren't all "code" (and so don't make sense to manage via the Code app).

**Comment by GammaGames** [comment]
I was just thinking about this and was not surprised to see you've already created an issue! I have a couple ideas, mainly inspired from how I use vscode for projects.

* Status badges
When in a git project, the files could have small badges that show git status. Different colors for unstaged, staged, untracked. They could look similar to how Apple does their status badges on Mac OS and iOS, or just be added as a badge to the file's icon.
![image](https://user-images.githubusercontent.com/7832163/62565165-7b273f00-b843-11e9-9de3-6ecfbb26955f.png)
* Last revision in list view
I don't know if I've ever really cared about last modified date when working with a project, but I do care about last revision, message, and user. I imagine it would look similar to how GitHub shows their list of files for projects.  
* Easy blame
I think it would be useful if we could right click a file and view its blame log in the default browser. The [Git Blame](https://marketplace.visualstudio.com/items?itemName=waderyan.gitblame) extension does this, but I don't always want to have vscode open to easily get a blame link for a file. I'm also not sure how consistent hosting sites are for link format, so that might be a larger undertaking than I first thought.
