### ISSUE TITLE
[Dark mode] Files - Search bar text color

### ISSUE THREAD

**Issue by mateuspv** [elementary/files#897]
The text on "Search or type Path" should use a white color.
![screenshot from 2019-02-27 14-50-25](https://user-images.githubusercontent.com/4995440/53511631-9aa18b00-3a9f-11e9-846f-b74dc2c5dfae.png)

**Comment by a-tokarev** [comment]
> and if we _were_ ever to support a system-wide dark preference

Dear @cassidyjames and all the other elementary OS developers! The Dark Mode is not an unnecessary embellishment. It is something very important and **elementary** (in the best sense of the word) for every user-friendly operating system. Not because it looks good. But simply because the Dark Mode in the long run seems to be a little safer for the one of your most precious assets: your eyes. I'm a middle-aged designer who spends countless hours every day staring at the screen, and I know how red eyes look like from my personal experience. And I'm pretty sure I'm not the only one on this planet. So the sooner you guys drop this "every other OS has a Dark Mode, so hey, let's be original and not have it" stance, the better - for user's health and satisfaction and for the brand too. (And, by the way, thank you for your hard work and dedication.)

**Comment by ryonakano** [comment]
![Screenshot from 2019-05-03 15-57-57](https://user-images.githubusercontent.com/26003928/57123343-68244f00-6dbc-11e9-8590-f95219cf51f9.png)

This should be fixed in the latest version of Files (4.1.8) which include a fix for this issue (#925).
