### ISSUE TITLE
Wrong icon in the dock bar

### ISSUE THREAD

**Issue by gclove** [elementary/files#939]
They are calendar and files applications.
And I'm using elementary OS 5.0 Juno

![1](https://user-images.githubusercontent.com/3645410/57267847-26ddb900-70b4-11e9-91f6-14fdaf3dfafd.png)

**Comment by peteruithoven** [comment]
Thanks for the report! Could you add more details? 
Is this permanent? Does it still show the wrong icons after a restart?
Did you do anything that might have caused this?

**Comment by ryonakano** [comment]
@gclove Aren't you running your system in Simplified Chinese? I think this is because a translator of Simplified Chinese had translated the icon strings by mistake. The following strings in Files:

https://github.com/elementary/files/blob/bfabe590f7d3254d25585d01e4bda29cd80bb0a1/po/extra/zh_CN.po#L41-L42

is the icon name, and actually should not be translated.

Regarding to Calendar, it seems it was fixed in https://github.com/elementary/calendar/commit/c0949bb889a53ad50c61b9cd268ff4c2299c63c5. However, there's no new release of Calendar after this fix, so the icon is not shown if you're using elementary OS in Simplified Chinese.

**Comment by jeremypw** [comment]
Note that the related .po file contains a comment against this entry warning that it should not, in fact be translated. See https://github.com/elementary/files/blob/master/po/extra/extra.pot

**Comment by Yakumo-Yukari** [comment]
It seems that this problem has not been resolved.

**Comment by ryonakano** [comment]
@Yakumo-Yukari The translation was fixed but unless a new release is published both in Files (and Calendar) this issue won't be resolved.

**Comment by Yakumo-Yukari** [comment]
@ryonakano Ok, thank you for your answer.

**Comment by ryonakano** [comment]
@Yakumo-Yukari A new version of Files seems to be [released](https://github.com/elementary/files/releases/tag/4.1.9). Could you install updates and check if this issue is fixed?

**Comment by Yakumo-Yukari** [comment]
@ryonakano Thanks!

**Comment by ryonakano** [comment]
@Yakumo-Yukari If you confirm the issue has been fixed, you may want to close this issue.

**Comment by Yakumo-Yukari** [comment]
@ryonakano I can't close it, this is not a problem I submitted.

**Comment by ryonakano** [comment]
@Yakumo-Yukari Oops, I mistook you for @gclove. My apologies.

**Comment by gclove** [comment]
@ryonakano @Yakumo-Yukari   Oh, thank you very much! ❤️ 
I will confirm as soon as possible, then close it.
