### ISSUE TITLE
Auto strange refreshing folder view while in other windows file manager

### ISSUE THREAD

**Issue by alexsmedile** [elementary/files#96]
I discover that when I go back from one folder in _window1_ then _window2_ will refresh with home files + _windows2_ real files. Not always and not always in the same way.

**Comment by jeremypw** [comment]
Please could you explain this bug more clearly? i.e. give specific examples of which folder paths are open in each window, which view types are used, etc.

**Comment by rRexee** [comment]
Yes, sure. While I'm browsing a folder, and at the same time having another file manager window open in the same folder or a "relative" of that folder, sometime the file manager window in background auto refresh itself or it goes back when I go back in the main folder

**Comment by rRexee** [comment]
And, as I said before, it refresh with home files + folder files

**Comment by jeremypw** [comment]
OK, I can confirm that there is inconsistency in the refresh behaviour (using either the pathbar button or the F5 key).  The expected behaviour is that when both windows are showing the same folder, refreshing one window will refresh the other.  However, it is possible for this behaviour to become disconnected after navigating around before returning to both windows to show the same folder.

I cannot confirm the linked navigation effect you describe - and that would, in anycase have to be raised as a separate issue.

**Comment by jeremypw** [comment]
Closing this as it is not clear how to reproduce this issue.  Please open a new issue focussed on a single problem with steps to reproduce if it still occurs in the latest version.
